// src/pages/moderator/scanner-audit/[mode]/[label].tsx
/**
 * Focused single-label review for one (mode, label) pair.
 *
 * URL: /moderator/scanner-audit/[mode]/[label]
 *   mode: text | prompt | media → scanner: xguard_text | xguard_prompt | image_ingestion
 *
 * On mount, batch-fetches content for every item in the queue (chunked at the
 * tRPC schema's 50-per-call limit, parallel via Promise.all) so cycling through
 * the run feels instant after the initial load. Sidebar previews use real
 * content snippets once fetched, falling back to matched terms / hash while
 * pending.
 *
 * Keyboard: ← No, → Yes, ↓ Skip, ↑ Back. Yes/No map to TP/FP/TN/FN server-side
 * via the (modAnswer, modelTriggered) matrix.
 */
import {
  ActionIcon,
  Alert,
  Badge,
  Box,
  Button,
  Container,
  Drawer,
  Group,
  Image as MantineImage,
  Kbd,
  Loader,
  Paper,
  Progress,
  Stack,
  Text,
  Title,
  Tooltip,
} from '@mantine/core';
import { useClipboard } from '@mantine/hooks';
import {
  IconArrowDown,
  IconArrowLeft,
  IconArrowUp,
  IconCheck,
  IconChevronRight,
  IconCode,
  IconCopy,
  IconX,
  IconZoomIn,
  IconZoomOut,
} from '@tabler/icons-react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import type { ReactElement } from 'react';
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import { Meta } from '~/components/Meta/Meta';
import { Page } from '~/components/AppLayout/Page';
import { AppLayout } from '~/components/AppLayout/AppLayout';
import { ScrollArea } from '~/components/ScrollArea/ScrollArea';
import {
  isValidMode,
  modeToScanner,
  type ScannerAuditMode,
} from '~/components/Moderator/ScannerAuditLayout';
import { createServerSideProps } from '~/server/utils/server-side-helpers';
import type { Scanner } from '~/server/schema/scanner-review.schema';
import type { AggregatedScanRow } from '~/server/services/scanner-review.service';
import type { ScanContent } from '~/server/services/scanner-content.service';
import { ReviewVerdict } from '~/shared/utils/prisma/enums';
import { showErrorNotification } from '~/utils/notifications';
import { trpc } from '~/utils/trpc';

export const getServerSideProps = createServerSideProps({
  useSession: true,
  resolver: async ({ session }) => {
    if (!session || !session.user?.isModerator)
      return { redirect: { destination: '/', permanent: false } };
    return { props: {} };
  },
});

const DEFAULT_FONT_SIZE = 16;
const MIN_FONT_SIZE = 12;
const MAX_FONT_SIZE = 24;
const CONTENT_PREFETCH_LOOKAHEAD = 5;

// Shared cursor state between the page body (FocusedRun) and the sidebar that
// lives in AppLayout's `right` slot. Items themselves come from the trpc
// query, which is called in both places — React Query dedupes by key so we
// only pay for the network round-trip once.
type FocusedCursorCtx = {
  cursor: number;
  setCursor: (c: number | ((c: number) => number)) => void;
};
const FocusedCursorContext = createContext<FocusedCursorCtx | null>(null);

function useFocusedCursor() {
  const ctx = useContext(FocusedCursorContext);
  if (!ctx) throw new Error('FocusedCursorContext required');
  return ctx;
}

function FocusedRunLayout({ children }: { children: ReactElement }) {
  const [cursor, setCursor] = useState(0);
  return (
    <FocusedCursorContext.Provider value={{ cursor, setCursor }}>
      <AppLayout scrollable={false} right={<FocusedRunSidebarMount />}>
        {children}
      </AppLayout>
    </FocusedCursorContext.Provider>
  );
}

function FocusedRunSidebarMount() {
  const router = useRouter();
  const modeParam = Array.isArray(router.query.mode) ? router.query.mode[0] : router.query.mode;
  const labelParam = Array.isArray(router.query.label) ? router.query.label[0] : router.query.label;
  const lookbackDays = router.query.lookbackDays ? Number(router.query.lookbackDays) : undefined;
  const validMode = isValidMode(modeParam) ? modeParam : null;

  const { data } = trpc.scannerReview.focusedRun.useQuery(
    {
      scanner: validMode ? modeToScanner(validMode) : 'xguard_text',
      label: labelParam ?? '',
      lookbackDays,
      limit: 50,
    },
    { enabled: !!validMode && !!labelParam, refetchOnWindowFocus: false }
  );
  const items = data?.items ?? [];
  const { cursor, setCursor } = useFocusedCursor();

  if (items.length === 0) return null;
  return <ProgressSidebar items={items} cursor={cursor} onJump={setCursor} />;
}

function ScannerAuditFocusedPage() {
  const router = useRouter();
  const modeParam = Array.isArray(router.query.mode) ? router.query.mode[0] : router.query.mode;
  const labelParam = Array.isArray(router.query.label) ? router.query.label[0] : router.query.label;
  const lookbackDays = router.query.lookbackDays ? Number(router.query.lookbackDays) : undefined;

  if (!isValidMode(modeParam) || !labelParam) {
    if (typeof window !== 'undefined') router.replace('/moderator/scanner-audit');
    return null;
  }

  return (
    <>
      <Meta title={`Scanner Audit · ${labelParam}`} deIndex />
      <FocusedRun
        mode={modeParam}
        scanner={modeToScanner(modeParam)}
        label={labelParam}
        lookbackDays={lookbackDays}
      />
    </>
  );
}

function FocusedRun({
  mode,
  scanner,
  label,
  lookbackDays,
}: {
  mode: ScannerAuditMode;
  scanner: Scanner;
  label: string;
  lookbackDays?: number;
}) {
  const router = useRouter();
  const utils = trpc.useUtils();
  const { cursor, setCursor } = useFocusedCursor();
  const [fontSize, setFontSize] = useState(DEFAULT_FONT_SIZE);

  const { data, isLoading, refetch } = trpc.scannerReview.focusedRun.useQuery(
    { scanner, label, lookbackDays, limit: 50 },
    { refetchOnWindowFocus: false }
  );

  const items = useMemo(() => data?.items ?? [], [data?.items]);
  const current = items[cursor];

  // Resolve content for the current item only. As the cursor advances, the
  // input key changes and React Query either fires a new request or — if the
  // item was prefetched — returns the cached result instantly.
  const currentContentQuery = trpc.scannerReview.focusedItemContent.useQuery(
    {
      contentHash: current?.contentHash ?? '',
      workflowId: current?.workflowIds[0] ?? '',
      scanner: current?.scanner ?? '',
      entityIds: current?.entityIds ?? [],
    },
    { enabled: !!current, refetchOnWindowFocus: false, staleTime: 5 * 60 * 1000 }
  );
  const currentContent = currentContentQuery.data;

  // Look ahead and prefetch content for the next CONTENT_PREFETCH_LOOKAHEAD
  // items so cursor advances feel instant. Prefetches are fire-and-forget
  // and share the React Query cache with the active query above.
  useEffect(() => {
    if (items.length === 0) return;
    for (let i = 1; i <= CONTENT_PREFETCH_LOOKAHEAD; i++) {
      const it = items[cursor + i];
      if (!it) break;
      utils.scannerReview.focusedItemContent.prefetch(
        {
          contentHash: it.contentHash,
          workflowId: it.workflowIds[0] ?? '',
          scanner: it.scanner,
          entityIds: it.entityIds,
        },
        { staleTime: 5 * 60 * 1000 }
      );
    }
  }, [cursor, items, utils]);

  const upsertVerdict = trpc.scannerReview.upsertVerdict.useMutation({
    onError: (err) =>
      showErrorNotification({ title: 'Verdict failed', error: new Error(err.message) }),
  });

  const submitAnswer = useCallback(
    (modSaysShouldTrigger: boolean) => {
      if (!current) return;
      const verdict = verdictFromAnswer(current.triggered === 1, modSaysShouldTrigger);
      const snap = currentContent;
      const body =
        snap && !snap.unavailable
          ? {
              text: snap.text,
              positivePrompt: snap.positivePrompt,
              negativePrompt: snap.negativePrompt,
              imageId: snap.imageId,
              labelReasons: snap.labelReasons,
              userId: snap.userId,
            }
          : undefined;
      upsertVerdict.mutate({
        contentHash: current.contentHash,
        version: current.version,
        label: current.label,
        verdict,
        contentSnapshot: body ? { scanner: current.scanner, body } : undefined,
      });
      setCursor((c) => Math.min(c + 1, items.length));
    },
    [current, currentContent, items.length, upsertVerdict, setCursor]
  );

  const skip = useCallback(
    () => setCursor((c) => Math.min(c + 1, items.length)),
    [items.length, setCursor]
  );
  const back = useCallback(() => setCursor((c) => Math.max(c - 1, 0)), [setCursor]);
  const zoomIn = useCallback(() => setFontSize((f) => Math.min(f + 2, MAX_FONT_SIZE)), []);
  const zoomOut = useCallback(() => setFontSize((f) => Math.max(f - 2, MIN_FONT_SIZE)), []);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
      switch (e.key) {
        case 'ArrowLeft':
          e.preventDefault();
          submitAnswer(false);
          break;
        case 'ArrowRight':
          e.preventDefault();
          submitAnswer(true);
          break;
        case 'ArrowDown':
          e.preventDefault();
          skip();
          break;
        case 'ArrowUp':
          e.preventDefault();
          back();
          break;
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [submitAnswer, skip, back]);

  const tablePath = `/moderator/scanner-audit/${mode}`;

  if (isLoading) {
    return (
      <Container py="xl">
        <Group justify="center">
          <Loader />
        </Group>
      </Container>
    );
  }

  if (!data || items.length === 0 || cursor >= items.length) {
    return (
      <EndOfRun
        label={label}
        completed={cursor}
        total={items.length}
        verdictedInLookback={data?.verdictedInLookback ?? 0}
        lookbackDays={data?.lookbackDays ?? 30}
        tablePath={tablePath}
        onExtendLookback={() => {
          const next = (lookbackDays ?? 30) + 30;
          setCursor(0);
          router.push({
            pathname: `/moderator/scanner-audit/${mode}/${encodeURIComponent(label)}`,
            query: { lookbackDays: String(next) },
          });
          refetch();
        }}
      />
    );
  }

  return (
    <div className="flex flex-1 flex-col overflow-hidden">
      <ScrollArea className="flex-1">
        <Container size="md" py="lg">
          <Stack gap="lg">
            <ItemHeader
              scanner={scanner}
              label={label}
              item={current}
              content={currentContent}
              cursor={cursor}
              total={items.length}
              fontSize={fontSize}
              onZoomIn={zoomIn}
              onZoomOut={zoomOut}
              onExit={() => router.push(tablePath)}
            />
            <TriggerBanner item={current} />
            <ContentDisplay item={current} content={currentContent} fontSize={fontSize} />
          </Stack>
        </Container>
      </ScrollArea>
      <ActionFooter
        disabled={upsertVerdict.isLoading}
        onNo={() => submitAnswer(false)}
        onYes={() => submitAnswer(true)}
        onSkip={skip}
        onBack={back}
        canBack={cursor > 0}
      />
    </div>
  );
}

function ItemHeader({
  scanner,
  label,
  item,
  content,
  cursor,
  total,
  fontSize,
  onZoomIn,
  onZoomOut,
  onExit,
}: {
  scanner: Scanner;
  label: string;
  item: AggregatedScanRow;
  content: ScanContent | undefined;
  cursor: number;
  total: number;
  fontSize: number;
  onZoomIn: () => void;
  onZoomOut: () => void;
  onExit: () => void;
}) {
  const clipboard = useClipboard({ timeout: 1500 });
  const [showRaw, setShowRaw] = useState(false);
  const primaryWorkflowId = item.workflowIds[0] ?? '';
  const modelReason = content?.labelReasons?.[item.label];

  return (
    <Stack gap="md">
      <Group justify="space-between" align="flex-start" wrap="nowrap">
        <Stack gap={4} style={{ flex: 1, minWidth: 0 }}>
          <Group gap="xs">
            <Text c="dimmed" size="xs" tt="uppercase" fw={500}>
              Label
            </Text>
            <Badge variant="light" size="xs">
              {scanner.replace('xguard_', '').replace('image_ingestion', 'image')}
            </Badge>
          </Group>
          <Title order={1} style={{ fontFamily: 'monospace', fontSize: 32, lineHeight: 1.2 }}>
            {label}
          </Title>
        </Stack>
        <Group gap="xs" wrap="nowrap">
          <Tooltip label={clipboard.copied ? 'Copied!' : 'Copy workflow ID'}>
            <ActionIcon
              variant="default"
              size="lg"
              onClick={() => clipboard.copy(primaryWorkflowId)}
              disabled={!primaryWorkflowId}
              color={clipboard.copied ? 'green' : undefined}
            >
              {clipboard.copied ? <IconCheck size={16} /> : <IconCopy size={16} />}
            </ActionIcon>
          </Tooltip>
          <Tooltip label="View raw workflow JSON">
            <ActionIcon
              variant="default"
              size="lg"
              onClick={() => setShowRaw(true)}
              disabled={!primaryWorkflowId}
            >
              <IconCode size={16} />
            </ActionIcon>
          </Tooltip>
          <Tooltip label="Smaller text">
            <ActionIcon
              variant="default"
              size="lg"
              onClick={onZoomOut}
              disabled={fontSize <= MIN_FONT_SIZE}
            >
              <IconZoomOut size={16} />
            </ActionIcon>
          </Tooltip>
          <Tooltip label="Larger text">
            <ActionIcon
              variant="default"
              size="lg"
              onClick={onZoomIn}
              disabled={fontSize >= MAX_FONT_SIZE}
            >
              <IconZoomIn size={16} />
            </ActionIcon>
          </Tooltip>
          <Tooltip label="Back to table">
            <ActionIcon variant="default" size="lg" onClick={onExit}>
              <IconX size={16} />
            </ActionIcon>
          </Tooltip>
        </Group>
      </Group>

      {showRaw && primaryWorkflowId && (
        <WorkflowRawDrawer workflowId={primaryWorkflowId} onClose={() => setShowRaw(false)} />
      )}

      <Group gap="xs" wrap="wrap">
        {content?.userId && (
          <Badge
            component={Link}
            href={`/user-id/${content.userId}`}
            target="_blank"
            variant="filled"
            color="blue"
            size="sm"
            style={{ cursor: 'pointer', textTransform: 'none' }}
          >
            user {content.userId}
          </Badge>
        )}
        {item.labelValue && (
          <Badge variant="outline" size="sm">
            value: {item.labelValue}
          </Badge>
        )}
        <Badge variant="outline" size="sm">
          {item.occurrences.toLocaleString()} occurrences
        </Badge>
      </Group>

      {modelReason && (
        <Text size="sm" c="dimmed" style={{ whiteSpace: 'pre-wrap', fontStyle: 'italic' }}>
          {modelReason}
        </Text>
      )}

      {item.matchedText.length > 0 && <MatchedTermsRow label="Matched" terms={item.matchedText} />}
      {item.matchedPositivePrompt.length > 0 && (
        <MatchedTermsRow label="Matched (positive)" terms={item.matchedPositivePrompt} />
      )}
      {item.matchedNegativePrompt.length > 0 && (
        <MatchedTermsRow label="Matched (negative)" terms={item.matchedNegativePrompt} />
      )}

      <Progress value={(cursor / Math.max(total, 1)) * 100} size="xs" />
      <Text size="xs" c="dimmed" ta="right">
        {cursor + 1} of {total}
      </Text>
    </Stack>
  );
}

function WorkflowRawDrawer({ workflowId, onClose }: { workflowId: string; onClose: () => void }) {
  const { data, isLoading } = trpc.scannerReview.getWorkflowRaw.useQuery({ workflowId });

  return (
    <Drawer
      opened
      onClose={onClose}
      position="right"
      size={1200}
      title={
        <Group gap="xs">
          <Text fw={600}>Raw workflow</Text>
          <Text ff="monospace" size="xs" c="dimmed">
            {workflowId}
          </Text>
        </Group>
      }
    >
      {isLoading ? (
        <Group justify="center" py="xl">
          <Loader size="sm" />
        </Group>
      ) : data === null || data === undefined ? (
        <Alert color="yellow">
          Workflow not found in orchestrator. It may have expired past the 30-day retention window.
        </Alert>
      ) : (
        <Box
          component="pre"
          style={{
            margin: 0,
            padding: 12,
            background: 'var(--mantine-color-default-hover)',
            borderRadius: 4,
            fontFamily: 'monospace',
            fontSize: 12,
            lineHeight: 1.5,
            whiteSpace: 'pre-wrap',
            wordBreak: 'break-word',
            maxHeight: 'calc(100vh - 120px)',
            overflowY: 'auto',
          }}
        >
          {JSON.stringify(data, null, 2)}
        </Box>
      )}
    </Drawer>
  );
}

function MatchedTermsRow({ label, terms }: { label: string; terms: string[] }) {
  return (
    <Group gap={6} wrap="wrap" align="center">
      <Text size="xs" c="dimmed" fw={500}>
        {label}:
      </Text>
      {terms.map((t, i) => (
        <Badge
          key={`${t}-${i}`}
          size="sm"
          variant="light"
          color="orange"
          styles={{ root: { textTransform: 'none', fontWeight: 500 } }}
        >
          {t}
        </Badge>
      ))}
    </Group>
  );
}

function TriggerBanner({ item }: { item: AggregatedScanRow }) {
  const triggered = item.triggered === 1;
  return (
    <Group gap="sm" wrap="nowrap">
      <Badge
        size="lg"
        radius="sm"
        color={triggered ? 'red' : 'gray'}
        variant={triggered ? 'filled' : 'light'}
        styles={{ root: { textTransform: 'uppercase', letterSpacing: 1 } }}
      >
        {triggered ? 'Triggered' : 'Not Triggered'}
      </Badge>
      <Text size="sm" c="dimmed">
        score {item.score.toFixed(3)}
        {item.threshold !== null && ` / threshold ${item.threshold.toFixed(2)}`}
      </Text>
    </Group>
  );
}

function ContentDisplay({
  item,
  content,
  fontSize,
}: {
  item: AggregatedScanRow;
  content: ScanContent | undefined;
  fontSize: number;
}) {
  if (!content) {
    return (
      <Paper p="xl" withBorder>
        <Group justify="center">
          <Loader size="sm" />
          <Text c="dimmed">Loading content…</Text>
        </Group>
      </Paper>
    );
  }
  if (content.unavailable) {
    return (
      <Alert color="yellow" title="Content unavailable">
        <Stack gap={4}>
          <Text size="sm">
            Couldn&apos;t resolve content for this item. You can still record a verdict.
          </Text>
          {content.unavailableReason && (
            <Text size="xs" c="dimmed" ff="monospace">
              {content.unavailableReason}
            </Text>
          )}
        </Stack>
      </Alert>
    );
  }

  if (item.scanner === 'image_ingestion' && content.imageUrl) {
    return (
      <Paper p="md" withBorder>
        <Group justify="center">
          <MantineImage
            src={content.imageUrl}
            alt={`image ${content.imageId}`}
            fit="contain"
            mah={500}
          />
        </Group>
      </Paper>
    );
  }

  const textStyle = {
    whiteSpace: 'pre-wrap' as const,
    overflowWrap: 'anywhere' as const,
    lineHeight: 1.6,
    fontSize,
  };

  if (item.scanner === 'xguard_text') {
    return (
      <Paper p="lg" withBorder>
        <Text style={textStyle}>{renderHighlighted(content.text ?? '', item.matchedText)}</Text>
      </Paper>
    );
  }

  return (
    <Stack gap="sm">
      <Paper p="lg" withBorder>
        <Text size="xs" fw={500} c="dimmed" mb="xs" tt="uppercase">
          Positive prompt
        </Text>
        <Text style={textStyle}>
          {renderHighlighted(content.positivePrompt ?? '', item.matchedPositivePrompt)}
        </Text>
      </Paper>
      {content.negativePrompt && (
        <Paper p="lg" withBorder>
          <Text size="xs" fw={500} c="dimmed" mb="xs" tt="uppercase">
            Negative prompt
          </Text>
          <Text style={textStyle}>
            {renderHighlighted(content.negativePrompt, item.matchedNegativePrompt)}
          </Text>
        </Paper>
      )}
    </Stack>
  );
}

function ActionFooter({
  disabled,
  onNo,
  onYes,
  onSkip,
  onBack,
  canBack,
}: {
  disabled: boolean;
  onNo: () => void;
  onYes: () => void;
  onSkip: () => void;
  onBack: () => void;
  canBack: boolean;
}) {
  return (
    <Box
      style={{
        borderTop: '1px solid var(--mantine-color-default-border)',
        background: 'var(--mantine-color-body)',
        padding: '16px 24px',
        flexShrink: 0,
      }}
    >
      <Group justify="center" gap="sm">
        <Button
          size="lg"
          variant="filled"
          color="red"
          leftSection={<IconArrowLeft size={18} />}
          rightSection={<Kbd>←</Kbd>}
          onClick={onNo}
          disabled={disabled}
          w={200}
        >
          No
        </Button>
        <Button
          size="md"
          variant="default"
          leftSection={<IconArrowUp size={16} />}
          rightSection={<Kbd>↑</Kbd>}
          onClick={onBack}
          disabled={disabled || !canBack}
          w={140}
        >
          Back
        </Button>
        <Button
          size="md"
          variant="default"
          leftSection={<IconArrowDown size={16} />}
          rightSection={<Kbd>↓</Kbd>}
          onClick={onSkip}
          disabled={disabled}
          w={140}
        >
          Skip
        </Button>
        <Button
          size="lg"
          variant="filled"
          color="green"
          leftSection={<IconCheck size={18} />}
          rightSection={<Kbd>→</Kbd>}
          onClick={onYes}
          disabled={disabled}
          w={200}
        >
          Yes
        </Button>
      </Group>
    </Box>
  );
}

const SIDEBAR_MATCHED_TERMS_MAX = 4;

function ProgressSidebar({
  items,
  cursor,
  onJump,
}: {
  items: AggregatedScanRow[];
  cursor: number;
  onJump: (idx: number) => void;
}) {
  // AppLayout's `right` slot already wraps this in an <aside> with
  // `scroll-area` (overflow handling) and a left border — we just set width.
  return (
    <Box style={{ width: 320 }}>
      <Stack gap={2} p="md">
        <Group justify="space-between" mb="xs">
          <Text fw={600}>Run</Text>
          <Text size="xs" c="dimmed">
            {cursor + 1} of {items.length}
          </Text>
        </Group>
        {items.map((it, idx) => {
          const isCurrent = idx === cursor;
          const isPast = idx < cursor;
          const matched = [
            ...it.matchedText,
            ...it.matchedPositivePrompt,
            ...it.matchedNegativePrompt,
          ];
          const matchedVisible = matched.slice(0, SIDEBAR_MATCHED_TERMS_MAX);
          const matchedOverflow = matched.length - matchedVisible.length;
          return (
            <Box
              key={`${it.contentHash}-${it.version}`}
              onClick={() => onJump(idx)}
              p="xs"
              style={{
                cursor: 'pointer',
                borderRadius: 4,
                background: isCurrent ? 'var(--mantine-color-blue-9)' : 'transparent',
                opacity: isPast ? 0.55 : 1,
              }}
            >
              <Group gap="xs" wrap="nowrap" align="flex-start">
                <Box
                  style={{
                    width: 8,
                    height: 8,
                    borderRadius: '50%',
                    marginTop: 6,
                    background: isPast
                      ? 'var(--mantine-color-gray-6)'
                      : it.triggered === 1
                      ? 'var(--mantine-color-red-6)'
                      : 'var(--mantine-color-gray-5)',
                    flexShrink: 0,
                  }}
                />
                <Stack gap={4} style={{ minWidth: 0, flex: 1 }}>
                  <Text size="xs" c="dimmed">
                    {it.score.toFixed(3)}
                    {it.threshold !== null && ` / ${it.threshold.toFixed(2)}`}
                  </Text>
                  {matched.length > 0 ? (
                    <Group gap={4} wrap="wrap">
                      {matchedVisible.map((t, i) => (
                        <Badge
                          key={`${t}-${i}`}
                          size="xs"
                          variant="light"
                          color="orange"
                          styles={{ root: { textTransform: 'none', fontWeight: 500 } }}
                        >
                          {t}
                        </Badge>
                      ))}
                      {matchedOverflow > 0 && (
                        <Text size="xs" c="dimmed">
                          +{matchedOverflow}
                        </Text>
                      )}
                    </Group>
                  ) : (
                    <Text size="xs" c="dimmed" lineClamp={1}>
                      {it.contentHash.slice(0, 12)}
                    </Text>
                  )}
                </Stack>
              </Group>
            </Box>
          );
        })}
      </Stack>
    </Box>
  );
}

function EndOfRun({
  label,
  completed,
  total,
  verdictedInLookback,
  lookbackDays,
  tablePath,
  onExtendLookback,
}: {
  label: string;
  completed: number;
  total: number;
  verdictedInLookback: number;
  lookbackDays: number;
  tablePath: string;
  onExtendLookback: () => void;
}) {
  return (
    <Container size="sm" py="xl">
      <Paper p="xl" withBorder>
        <Stack gap="lg">
          <Stack gap={4}>
            <Title order={2}>Run complete</Title>
            <Text c="dimmed">
              {total === 0
                ? `No unverdicted scans for ${label} in the current lookback window.`
                : `You reviewed ${completed} of ${total} scans for ${label}.`}
              {verdictedInLookback > 0 && (
                <>
                  {' '}
                  (You&apos;ve verdicted {verdictedInLookback.toLocaleString()} {label} scan
                  {verdictedInLookback === 1 ? '' : 's'} in the last {lookbackDays} days.)
                </>
              )}
            </Text>
          </Stack>
          <Stack gap="sm">
            <Button
              component={Link}
              href={tablePath}
              variant="default"
              leftSection={<IconArrowLeft size={16} />}
            >
              Back to table
            </Button>
            <Button
              component={Link}
              href={tablePath}
              variant="default"
              leftSection={<IconChevronRight size={16} />}
            >
              Switch label
            </Button>
            <Button onClick={onExtendLookback}>Grab more (extend lookback by 30 days)</Button>
          </Stack>
        </Stack>
      </Paper>
    </Container>
  );
}

function verdictFromAnswer(modelTriggered: boolean, modSaysShouldTrigger: boolean): ReviewVerdict {
  if (modelTriggered) {
    return modSaysShouldTrigger ? ReviewVerdict.TruePositive : ReviewVerdict.FalsePositive;
  }
  return modSaysShouldTrigger ? ReviewVerdict.FalseNegative : ReviewVerdict.TrueNegative;
}

function renderHighlighted(text: string, terms: string[]) {
  if (!text) return null;
  if (terms.length === 0) return text;

  const sorted = [...new Set(terms)].sort((a, b) => b.length - a.length);
  const escaped = sorted.map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  const regex = new RegExp(`(${escaped.join('|')})`, 'gi');
  const termsLower = new Set(terms.map((t) => t.toLowerCase()));

  const parts = text.split(regex);
  return parts.map((part, i) =>
    termsLower.has(part.toLowerCase()) ? (
      <mark
        key={i}
        style={{
          background: '#fbbf24', // amber-400 — readable on both dark and light bodies
          color: '#111827', // gray-900 forces dark text regardless of theme
          padding: '1px 4px',
          borderRadius: 3,
          fontWeight: 500,
        }}
      >
        {part}
      </mark>
    ) : (
      part
    )
  );
}

export default Page(ScannerAuditFocusedPage, {
  getLayout: (page) => <FocusedRunLayout>{page}</FocusedRunLayout>,
});

// apps/moderator/src/routes/audit/scanner-audit/[mode]/[label]/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { page } from '$app/state';
  import { SvelteMap } from 'svelte/reactivity';
  import { IconCode, IconX, IconCopy, IconCheck, IconZoomIn, IconZoomOut } from '@tabler/icons-svelte';
  import { Button } from '@civitai/ui/components/ui/button/index.js';
  import { Badge } from '@civitai/ui/components/ui/badge/index.js';
  import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@civitai/ui/components/ui/sheet/index.js';
  import EdgeMedia from '$lib/components/EdgeMedia.svelte';
  import { verdictFromAnswer, type ScanContent } from '$lib/scanner-audit';
  import { computeHighlightSegments, HIGHLIGHT_STYLES, getScannerLabelPolicy } from '@civitai/mod-utils';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();

  const items = $derived(data.items);
  const base = $derived(page.url.pathname);

  let cursor = $state(0);
  $effect(() => {
    data.items; // reset when a new run loads (filter/lookback change)
    cursor = 0;
  });

  const current = $derived(items[cursor]);
  const done = $derived(items.length === 0 || cursor >= items.length);

  // Content cache (resolved lazily per item + prefetch a few ahead).
  const contentCache = new SvelteMap<string, ScanContent>();
  const inflight = new Set<string>();

  function contentParams(it: (typeof items)[number]): string {
    const p = new URLSearchParams({
      contentHash: it.contentHash,
      workflowId: it.workflowIds[0] ?? '',
      scanner: it.scanner,
    });
    for (const e of it.entityIds) p.append('entityId', e);
    return p.toString();
  }

  async function ensureContent(it: (typeof items)[number] | undefined) {
    if (!it || contentCache.has(it.contentHash) || inflight.has(it.contentHash)) return;
    inflight.add(it.contentHash);
    try {
      const res = await fetch(`${base}/content?${contentParams(it)}`);
      if (res.ok) contentCache.set(it.contentHash, await res.json());
    } finally {
      inflight.delete(it.contentHash);
    }
  }

  $effect(() => {
    cursor;
    for (let i = 0; i <= 4; i++) ensureContent(items[cursor + i]);
  });

  const currentContent = $derived(current ? (contentCache.get(current.contentHash) ?? null) : null);

  async function submitAnswer(shouldTrigger: boolean) {
    const item = current;
    if (!item) return;
    const verdict = verdictFromAnswer(item.triggered === 1, shouldTrigger);
    const content = contentCache.get(item.contentHash);
    const body =
      content && !content.unavailable
        ? {
            text: content.text,
            positivePrompt: content.positivePrompt,
            negativePrompt: content.negativePrompt,
            imageId: content.imageId,
            labelReasons: content.labelReasons,
            userId: content.userId,
          }
        : undefined;
    cursor = Math.min(cursor + 1, items.length); // optimistic advance
    try {
      await fetch(`${base}/verdict`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          contentHash: item.contentHash,
          version: item.version,
          label: item.label,
          verdict,
          scanner: item.scanner,
          content: body,
        }),
      });
    } catch {
      /* optimistic — a failed verdict just won't be recorded; mod can revisit */
    }
  }

  const skip = () => (cursor = Math.min(cursor + 1, items.length));
  const back = () => (cursor = Math.max(cursor - 1, 0));

  $effect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
      if (done) return;
      if (e.key === 'ArrowLeft') (e.preventDefault(), submitAnswer(false));
      else if (e.key === 'ArrowRight') (e.preventDefault(), submitAnswer(true));
      else if (e.key === 'ArrowDown') (e.preventDefault(), skip());
      else if (e.key === 'ArrowUp') (e.preventDefault(), back());
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  });

  // Raw workflow drawer.
  let rawOpen = $state(false);
  let rawJson = $state<unknown>(undefined);
  let rawLoading = $state(false);
  async function openRaw(workflowId: string) {
    rawOpen = true;
    rawLoading = true;
    rawJson = undefined;
    try {
      const res = await fetch(`${base}/workflow?workflowId=${encodeURIComponent(workflowId)}`);
      rawJson = res.ok ? await res.json() : null;
    } finally {
      rawLoading = false;
    }
  }

  const tablePath = $derived(`/audit/scanner-audit/${data.mode}`);
  const scannerShort = $derived(data.scanner.replace('xguard_', '').replace('image_ingestion', 'image'));
  const policy = $derived(getScannerLabelPolicy(data.label));

  const MIN_FONT = 12;
  const MAX_FONT = 24;
  let fontSize = $state(16);
  const zoomOut = () => (fontSize = Math.max(fontSize - 2, MIN_FONT));
  const zoomIn = () => (fontSize = Math.min(fontSize + 2, MAX_FONT));

  let copiedId = $state(false);
  let copyTimer: ReturnType<typeof setTimeout> | undefined;
  async function copyWorkflowId(id: string) {
    try {
      await navigator.clipboard.writeText(id);
      copiedId = true;
      clearTimeout(copyTimer);
      copyTimer = setTimeout(() => (copiedId = false), 1500);
    } catch {
      /* clipboard unavailable */
    }
  }

  const hasMatched = $derived(
    !!current &&
      current.matchedText.length +
        current.matchedPositivePrompt.length +
        current.matchedNegativePrompt.length >
        0
  );
</script>

{#snippet highlighted(text: string, terms: string[], label: string)}{#each computeHighlightSegments(text, terms, label) as seg}{#if seg.source}<mark
        class="rounded px-1"
        style="background:{HIGHLIGHT_STYLES[seg.source].bg};color:#111827;font-weight:{HIGHLIGHT_STYLES[
          seg.source
        ].weight}"
        title={HIGHLIGHT_STYLES[seg.source].title}>{seg.text}</mark>{:else}{seg.text}{/if}{/each}{/snippet}

{#snippet policySection(heading: string, colorClass: string, items: string[])}
  {#if items.length > 0}
    <div>
      <div class="mb-1 text-xs font-semibold uppercase {colorClass}">{heading}</div>
      <ul class="list-disc space-y-1 pl-5 text-sm">
        {#each items as item}<li>{item}</li>{/each}
      </ul>
    </div>
  {/if}
{/snippet}

{#snippet matchedTerms(label: string, terms: string[])}
  {#if terms.length > 0}
    <div class="flex flex-wrap items-center gap-1.5">
      <span class="text-xs font-medium text-muted-foreground">{label}:</span>
      {#each terms as t}
        <Badge variant="outline" class="border-orange-400/40 bg-orange-400/10 font-normal text-orange-300"
          >{t}</Badge
        >
      {/each}
    </div>
  {/if}
{/snippet}

<!-- Full-bleed panel (layout drops its max-w wrapper via fullBleed): scrolling content column with a
     pinned footer on the left, full-height policy sidebar flush to the right. h-12 = the layout header. -->
<div class="flex h-[calc(100svh-3rem)]">
  <div class="flex min-w-0 flex-1 flex-col">
    <div class="flex-1 overflow-y-auto px-6 py-4">
    <div class="mx-auto flex max-w-3xl flex-col gap-4">
      <div class="flex items-start justify-between gap-2">
    <div class="flex flex-col gap-1">
      <div class="flex items-center gap-2">
        <span class="text-xs uppercase text-muted-foreground">Label</span>
        <Badge variant="secondary">{scannerShort}</Badge>
      </div>
      <h1 class="font-mono text-3xl">{data.label}</h1>
    </div>
    <Button variant="outline" size="sm" href={tablePath}><IconX size={14} /> Back to table</Button>
  </div>

  {#if done}
    <div class="rounded-xl border p-6">
      <h2 class="text-xl font-semibold">Run complete</h2>
      <p class="mt-1 text-sm text-muted-foreground">
        {items.length === 0
          ? `No unverdicted scans for ${data.label} in the current lookback window.`
          : `You reviewed ${cursor} of ${items.length} scans for ${data.label}.`}
        {#if data.verdictedInLookback > 0}
          (You've verdicted {data.verdictedInLookback.toLocaleString()} {data.label} scan{data
            .verdictedInLookback === 1
            ? ''
            : 's'} in the last {data.lookbackDays} days.)
        {/if}
      </p>
      <div class="mt-4 flex flex-col gap-2">
        <Button variant="outline" href={tablePath}>Back to table</Button>
        <Button onclick={() => goto(`${base}?lookbackDays=${(data.lookbackDays ?? 30) + 30}`)}>
          Grab more (extend lookback by 30 days)
        </Button>
      </div>
    </div>
  {:else if current}
    {@const c = currentContent}
    <div class="flex flex-col gap-3">
      <!-- header meta -->
      <div class="flex flex-wrap items-center gap-2">
        {#if c?.userId}
          <Badge class="bg-blue-500/15 text-blue-300">user {c.userId}</Badge>
        {/if}
        {#if current.labelValue}<Badge variant="outline">value: {current.labelValue}</Badge>{/if}
        <Badge variant="outline">{current.occurrences.toLocaleString()} occurrences</Badge>
        {#if current.workflowIds[0]}
          <Button variant="outline" size="sm" onclick={() => copyWorkflowId(current.workflowIds[0])}>
            {#if copiedId}<IconCheck size={14} />{:else}<IconCopy size={14} />{/if}
            {copiedId ? 'Copied' : 'Copy ID'}
          </Button>
          <Button variant="outline" size="sm" onclick={() => openRaw(current.workflowIds[0])}>
            <IconCode size={14} /> Raw workflow
          </Button>
        {/if}
        <div class="ml-auto flex items-center gap-1">
          <Button
            variant="outline"
            size="icon"
            class="size-8"
            title="Smaller text"
            onclick={zoomOut}
            disabled={fontSize <= MIN_FONT}
          >
            <IconZoomOut size={14} />
          </Button>
          <Button
            variant="outline"
            size="icon"
            class="size-8"
            title="Larger text"
            onclick={zoomIn}
            disabled={fontSize >= MAX_FONT}
          >
            <IconZoomIn size={14} />
          </Button>
        </div>
      </div>

      <div class="h-1 w-full overflow-hidden rounded bg-muted">
        <div
          class="h-full bg-primary transition-all"
          style="width:{(cursor / Math.max(items.length, 1)) * 100}%"
        ></div>
      </div>

      {#if c?.labelReasons?.[current.label]}
        <p class="text-sm italic text-muted-foreground">{c.labelReasons[current.label]}</p>
      {/if}

      <!-- trigger banner -->
      <div class="flex items-center gap-2">
        <Badge class={current.triggered === 1 ? 'bg-red-500/20 text-red-300' : 'bg-muted'}>
          {current.triggered === 1 ? 'TRIGGERED' : 'NOT TRIGGERED'}
        </Badge>
        <span class="text-sm text-muted-foreground">
          score {current.score.toFixed(3)}{current.threshold !== null
            ? ` / threshold ${current.threshold.toFixed(2)}`
            : ''}
        </span>
      </div>

      {#if hasMatched}
        <div class="flex flex-col gap-1.5">
          {@render matchedTerms('Matched', current.matchedText)}
          {@render matchedTerms('Matched (positive)', current.matchedPositivePrompt)}
          {@render matchedTerms('Matched (negative)', current.matchedNegativePrompt)}
        </div>
      {/if}

      <!-- content -->
      {#if !c}
        <div class="rounded-lg border p-6 text-center text-sm text-muted-foreground">Loading content…</div>
      {:else if c.unavailable}
        <div class="rounded-md border border-yellow-500/30 bg-yellow-500/10 p-3 text-sm text-yellow-300">
          Content unavailable — you can still record a verdict.
          {#if c.unavailableReason}<div class="mt-1 font-mono text-xs opacity-70">{c.unavailableReason}</div>{/if}
        </div>
      {:else if current.scanner === 'image_ingestion' && c.imageUrl}
        <div class="flex justify-center rounded-lg border p-3">
          <img src={c.imageUrl} alt={`image ${c.imageId}`} class="max-h-[500px] object-contain" />
        </div>
      {:else if current.scanner === 'xguard_text'}
        <div
          class="whitespace-pre-wrap rounded-lg border p-4 leading-relaxed"
          style="font-size:{fontSize}px"
        >
          {@render highlighted(c.text ?? '', current.matchedText, current.label)}
        </div>
      {:else}
        <div class="rounded-lg border p-4">
          <div class="mb-1 text-xs uppercase text-muted-foreground">Positive prompt</div>
          <div class="whitespace-pre-wrap leading-relaxed" style="font-size:{fontSize}px">
            {@render highlighted(c.positivePrompt ?? '', current.matchedPositivePrompt, current.label)}
          </div>
        </div>
        {#if c.negativePrompt}
          <div class="rounded-lg border p-4">
            <div class="mb-1 text-xs uppercase text-muted-foreground">Negative prompt</div>
            <div class="whitespace-pre-wrap leading-relaxed" style="font-size:{fontSize}px">
              {@render highlighted(c.negativePrompt, current.matchedNegativePrompt, current.label)}
            </div>
          </div>
        {/if}
      {/if}

      </div>
      {/if}
    </div>
  </div>

  {#if current && !done}
    <div class="shrink-0 border-t bg-background px-6 py-3">
      <div class="mx-auto flex max-w-3xl items-center justify-center gap-2">
        <Button variant="destructive" class="w-48" onclick={() => submitAnswer(false)}>← No</Button>
        <Button variant="outline" onclick={back} disabled={cursor === 0}>↑ Back</Button>
        <Button variant="outline" onclick={skip}>↓ Skip</Button>
        <Button class="w-48 bg-teal-600 hover:bg-teal-600" onclick={() => submitAnswer(true)}>Yes →</Button>
      </div>
      <p class="mx-auto mt-1 max-w-3xl text-center text-xs text-muted-foreground">
        {cursor + 1} of {items.length} · ← No · → Yes · ↓ Skip · ↑ Back — Yes/No map to TP/FP/TN/FN
      </p>
    </div>
    {/if}
  </div>

  {#if current && !done}
    <aside class="hidden w-[26rem] shrink-0 overflow-y-auto border-l bg-muted/20 px-4 py-4 lg:block">
      {#if !policy}
        <h2 class="font-mono text-lg">{data.label}</h2>
        <p class="mt-2 rounded-md border p-3 text-sm text-muted-foreground">
          No moderator policy summary on file for this label yet.
        </p>
      {:else}
        <div class="flex flex-col gap-4">
          <div>
            <div class="text-xs font-medium uppercase text-muted-foreground">Policy</div>
            <h2 class="font-mono text-xl font-semibold">{policy.title}</h2>
          </div>
          <div>
            <span class="mb-1 inline-block rounded bg-blue-500/15 px-1.5 py-0.5 text-xs font-medium text-blue-300">Catch</span>
            <p class="text-sm">{policy.catch}</p>
          </div>
          {@render policySection('Should fire on', 'text-green-400', policy.shouldFire)}
          {@render policySection('Should NOT fire on', 'text-red-400', policy.shouldNotFire)}
          {@render policySection('Gotchas', 'text-yellow-400', policy.gotchas ?? [])}
          <p class="text-xs text-muted-foreground">
            Only the <strong>positive prompt</strong> decides the verdict — terms appearing only in the
            negative prompt are avoidance signals.
          </p>
        </div>
      {/if}
    </aside>
  {/if}
</div>

<Sheet bind:open={rawOpen}>
  <SheetContent side="right" class="w-[92vw] overflow-y-auto sm:max-w-[84rem]">
    <SheetHeader><SheetTitle>Raw workflow</SheetTitle></SheetHeader>
    <div class="p-4">
      {#if rawLoading}
        <p class="text-sm text-muted-foreground">Loading…</p>
      {:else if rawJson === null || rawJson === undefined}
        <div class="rounded-md border border-yellow-500/30 bg-yellow-500/10 p-3 text-sm text-yellow-300">
          Workflow not found in orchestrator (may have expired past the 30-day retention window).
        </div>
      {:else}
        <pre class="overflow-auto rounded-md border bg-muted/40 p-3 text-xs">{JSON.stringify(rawJson, null, 2)}</pre>
      {/if}
    </div>
  </SheetContent>
</Sheet>
