// apps/moderator/src/routes/audit/scanner-audit/[mode]/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { page } from '$app/state';
  import { IconDownload } from '@tabler/icons-svelte';
  import { Tabs, TabsList, TabsTrigger } from '@civitai/ui/components/ui/tabs/index.js';
  import { Input } from '@civitai/ui/components/ui/input/index.js';
  import { Button } from '@civitai/ui/components/ui/button/index.js';
  import { Badge } from '@civitai/ui/components/ui/badge/index.js';
  import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
  } from '@civitai/ui/components/ui/table/index.js';
  import {
    Pagination,
    PaginationContent,
    PaginationEllipsis,
    PaginationItem,
    PaginationLink,
    PaginationNext,
    PaginationPrevious,
  } from '@civitai/ui/components/ui/pagination/index.js';
  import { SCANNER_MODES, verdictShort, verdictClass, VERDICT_ORDER } from '$lib/scanner-audit';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();

  const totalPages = $derived(Math.max(1, Math.ceil(data.total / data.limit)));
  const fmtDate = (d: string) => new Date(d).toLocaleString();

  function urlWith(params: Record<string, string | number | null>) {
    const url = new URL(page.url);
    for (const [k, v] of Object.entries(params)) {
      if (v === null || v === '') url.searchParams.delete(k);
      else url.searchParams.set(k, String(v));
    }
    return url.pathname + url.search;
  }

  function applyFilters(e: SubmitEvent) {
    e.preventDefault();
    const form = new FormData(e.currentTarget as HTMLFormElement);
    goto(
      urlWith({
        label: String(form.get('label') ?? '').trim() || null,
        version: String(form.get('version') ?? '').trim() || null,
        page: 1,
      })
    );
  }

  // Focused per-label review — in the spoke, same app.
  const labelHref = (label: string) =>
    `/audit/scanner-audit/${data.mode}/${encodeURIComponent(label)}`;

  const exportHref = $derived(
    (() => {
      const p = new URLSearchParams({ view: data.view });
      if (data.label) p.set('label', data.label);
      if (data.version) p.set('version', data.version);
      return `/audit/scanner-audit/${data.mode}/export?${p}`;
    })()
  );

  const coverageTotal = $derived(data.stats.active.reduce((sum, r) => sum + r.total, 0));
</script>

<header class="page-header flex flex-wrap items-center justify-between gap-2">
  <h1>Scanner Audit</h1>
  <Button href={exportHref} variant="outline" size="sm">
    <IconDownload size={14} /> Export CSV
  </Button>
</header>

<Tabs value={data.mode} onValueChange={(v) => v && goto(`/audit/scanner-audit/${v}`)} class="mb-4">
  <TabsList>
    {#each SCANNER_MODES as m (m.value)}
      <TabsTrigger value={m.value}>{m.label}</TabsTrigger>
    {/each}
  </TabsList>
</Tabs>

<form class="mb-4 flex flex-wrap items-end gap-2" onsubmit={applyFilters}>
  <div class="flex flex-col gap-1">
    <span class="text-xs font-medium text-muted-foreground">Label</span>
    <Input name="label" value={data.label} placeholder="e.g. csam" class="h-8 w-48" />
  </div>
  <div class="flex flex-col gap-1">
    <span class="text-xs font-medium text-muted-foreground">Policy version</span>
    <Input name="version" value={data.version} placeholder="version" class="h-8 w-56" />
  </div>
  <Button type="submit" size="sm" variant="outline">Search</Button>
</form>

<!-- Review coverage -->
<div class="mb-4 rounded-xl border p-3">
  <div class="mb-2 flex items-center justify-between">
    <span class="text-sm font-medium">Moderator review coverage</span>
    <span class="text-xs text-muted-foreground">
      {coverageTotal.toLocaleString()} reviews across {data.stats.active.length} labels
    </span>
  </div>
  {#if data.stats.active.length === 0}
    <p class="text-sm text-muted-foreground">No moderator reviews recorded yet for this scanner.</p>
  {:else}
    <div class="max-h-64 overflow-auto">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Label</TableHead>
            <TableHead>Reviews</TableHead>
            <TableHead>Mods</TableHead>
            <TableHead>Verdicts</TableHead>
            <TableHead>Last reviewed</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {#each data.stats.active as s (s.label)}
            <TableRow>
              <TableCell>
                <a href={labelHref(s.label)} class="font-mono underline">{s.label}</a>
              </TableCell>
              <TableCell>{s.total.toLocaleString()}</TableCell>
              <TableCell>{s.reviewers.toLocaleString()}</TableCell>
              <TableCell>
                <div class="flex flex-wrap gap-1">
                  {#each VERDICT_ORDER as v (v)}
                    {@const count = s[
                      v === 'TruePositive'
                        ? 'truePositive'
                        : v === 'FalsePositive'
                          ? 'falsePositive'
                          : v === 'TrueNegative'
                            ? 'trueNegative'
                            : v === 'FalseNegative'
                              ? 'falseNegative'
                              : 'unsure'
                    ]}
                    <Badge class={count === 0 ? 'bg-muted text-muted-foreground opacity-40' : verdictClass[v]}>
                      {verdictShort[v]} {count.toLocaleString()}
                    </Badge>
                  {/each}
                </div>
              </TableCell>
              <TableCell class="text-xs text-muted-foreground">
                {s.lastReviewedAt ? fmtDate(s.lastReviewedAt) : '—'}
              </TableCell>
            </TableRow>
          {/each}
        </TableBody>
      </Table>
    </div>
  {/if}
  {#if data.stats.retired.length > 0}
    <p class="mt-2 text-xs text-muted-foreground">
      Hidden — retired labels no longer produced by this scanner:
      {data.stats.retired.map((r) => `${r.label} (${r.total.toLocaleString()})`).join(', ')}
    </p>
  {/if}
</div>

<Tabs value={data.view} onValueChange={(v) => v && goto(urlWith({ view: v, page: 1 }))} class="mb-4">
  <TabsList>
    <TabsTrigger value="triggered">Triggered (FP review)</TabsTrigger>
    <TabsTrigger value="near-miss">Near-miss (FN review)</TabsTrigger>
  </TabsList>
</Tabs>

{#if data.rows.length === 0}
  <div class="placeholder">No {data.view} decisions match the current filters in the last 30 days.</div>
{:else}
  <div class="rounded-xl border">
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Label</TableHead>
          <TableHead>Score</TableHead>
          <TableHead>Threshold</TableHead>
          <TableHead>Occurrences</TableHead>
          <TableHead>Policy</TableHead>
          <TableHead>Status</TableHead>
          <TableHead>Last seen</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {#each data.rows as r (`${r.contentHash}::${r.version}::${r.label}`)}
          <TableRow>
            <TableCell>
              <a href={labelHref(r.label)} class="font-mono underline">{r.label}</a>
              {#if r.labelValue}<span class="ml-1 text-xs text-muted-foreground">= {r.labelValue}</span>{/if}
            </TableCell>
            <TableCell class="tabular-nums">{r.score.toFixed(3)}</TableCell>
            <TableCell class="tabular-nums">{r.threshold !== null ? r.threshold.toFixed(2) : '—'}</TableCell>
            <TableCell class="tabular-nums">{r.occurrences.toLocaleString()}</TableCell>
            <TableCell class="font-mono text-xs text-muted-foreground" title={r.version || '(none)'}>
              {r.version ? `${r.version.slice(0, 10)}…` : '—'}
            </TableCell>
            <TableCell>
              {#if r.myVerdict}
                <Badge class={verdictClass[r.myVerdict]}>{verdictShort[r.myVerdict]}</Badge>
              {:else if r.anyVerdict}
                <Badge class={verdictClass[r.anyVerdict]} title="Verdict from another moderator">
                  {verdictShort[r.anyVerdict]}
                </Badge>
              {/if}
            </TableCell>
            <TableCell class="whitespace-nowrap text-xs text-muted-foreground">
              {fmtDate(r.lastSeenAt)}
            </TableCell>
          </TableRow>
        {/each}
      </TableBody>
    </Table>
  </div>
{/if}

<div class="mt-4 flex flex-wrap items-center justify-between gap-2">
  <span class="text-sm text-muted-foreground">
    {data.total.toLocaleString()} matching decisions · page {data.page} of {totalPages}
  </span>
  <Pagination
    count={data.total}
    perPage={data.limit}
    page={data.page}
    onPageChange={(p) => p !== data.page && goto(urlWith({ page: p }))}
  >
    {#snippet children({ pages, currentPage })}
      <PaginationContent>
        <PaginationItem><PaginationPrevious /></PaginationItem>
        {#each pages as p (p.key)}
          {#if p.type === 'ellipsis'}
            <PaginationItem><PaginationEllipsis /></PaginationItem>
          {:else}
            <PaginationItem>
              <PaginationLink page={p} isActive={currentPage === p.value}>{p.value}</PaginationLink>
            </PaginationItem>
          {/if}
        {/each}
        <PaginationItem><PaginationNext /></PaginationItem>
      </PaginationContent>
    {/snippet}
  </Pagination>
</div>

// src/pages/moderator/scanner-audit/[mode]/index.tsx
/**
 * Scanner audit table for one mode (text / prompt / media). Tabs at the top
 * navigate between modes. Triggered / Near-miss sub-tabs filter the rows.
 * Click a label cell → /moderator/scanner-audit/[mode]/[label] for focused
 * review of that label.
 */
import {
  Alert,
  Badge,
  Box,
  Button,
  Center,
  Group,
  Loader,
  LoadingOverlay,
  Pagination,
  Paper,
  ScrollArea,
  Stack,
  Table,
  Tabs,
  Text,
  TextInput,
  Title,
  Tooltip,
} from '@mantine/core';
import { IconDownload, IconInfoCircle } from '@tabler/icons-react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useMemo, useState } from 'react';
import { Meta } from '~/components/Meta/Meta';
import { Page } from '~/components/AppLayout/Page';
import {
  ScannerAuditLayout,
  isValidMode,
  modeToScanner,
  type ScannerAuditMode,
} from '~/components/Moderator/ScannerAuditLayout';
import { createServerSideProps } from '~/server/utils/server-side-helpers';
import type { QueueView, Scanner } from '~/server/schema/scanner-review.schema';
import type { QueueRow } from '~/server/services/scanner-review.service';
import { ReviewVerdict } from '~/shared/utils/prisma/enums';
import { showErrorNotification } from '~/utils/notifications';
import { trpc } from '~/utils/trpc';

export const getServerSideProps = createServerSideProps({
  useSession: true,
  resolver: async ({ session }) => {
    if (!session || !session.user?.isModerator)
      return { redirect: { destination: '/', permanent: false } };
    return { props: {} };
  },
});

const PAGE_SIZE = 50;

type Filters = {
  label: string;
  version: string;
};

function ScannerAuditTablePage() {
  const router = useRouter();
  const modeParam = Array.isArray(router.query.mode) ? router.query.mode[0] : router.query.mode;
  const mode: ScannerAuditMode = isValidMode(modeParam) ? modeParam : 'text';
  const scanner = modeToScanner(mode);

  const [view, setView] = useState<QueueView>('triggered');
  // `draftFilters` tracks the input boxes; `filters` is what actually drives
  // the query. They sync only when the mod clicks Search or hits Enter — that
  // way typing "csam" doesn't fire one query per keystroke against ClickHouse.
  const [draftFilters, setDraftFilters] = useState<Filters>({ label: '', version: '' });
  const [filters, setFilters] = useState<Filters>({ label: '', version: '' });
  const [page, setPage] = useState(1);

  const applyFilters = () => {
    setFilters(draftFilters);
    setPage(1);
  };

  const queryInput = useMemo(
    () => ({
      view,
      scanner,
      label: filters.label || undefined,
      version: filters.version || undefined,
      limit: PAGE_SIZE,
      offset: (page - 1) * PAGE_SIZE,
    }),
    [view, scanner, filters, page]
  );

  const { data, isFetching } = trpc.scannerReview.list.useQuery(queryInput);

  const totalPages = data ? Math.max(1, Math.ceil(data.total / PAGE_SIZE)) : 1;

  return (
    <>
      <Meta title="Scanner Audit" deIndex />
      <ScannerAuditLayout
        activeMode={mode}
        rightAction={<ExportButton view={view} mode={mode} filters={filters} />}
      >
        <Group align="end">
          <TextInput
            label="Label"
            placeholder="e.g. csam"
            value={draftFilters.label}
            onChange={(e) => {
              // Capture the value synchronously; React's synthetic event is
              // recycled by the time the updater function runs, so
              // `e.currentTarget` would be null inside it.
              const value = e.currentTarget.value;
              setDraftFilters((f) => ({ ...f, label: value }));
            }}
            onKeyDown={(e) => {
              if (e.key === 'Enter') applyFilters();
            }}
            size="xs"
            w={200}
          />
          <TextInput
            label="Policy version"
            placeholder="version"
            value={draftFilters.version}
            onChange={(e) => {
              const value = e.currentTarget.value;
              setDraftFilters((f) => ({ ...f, version: value }));
            }}
            onKeyDown={(e) => {
              if (e.key === 'Enter') applyFilters();
            }}
            size="xs"
            w={240}
          />
          <Button size="xs" onClick={applyFilters} loading={isFetching}>
            Search
          </Button>
        </Group>

        <ReviewCoveragePanel scanner={scanner} mode={mode} />

        <Tabs
          value={view}
          onChange={(v) => {
            if (v) {
              setView(v as QueueView);
              setPage(1);
            }
          }}
        >
          <Tabs.List>
            <Tabs.Tab value="triggered">Triggered (FP review)</Tabs.Tab>
            <Tabs.Tab value="near-miss">Near-miss (FN review)</Tabs.Tab>
          </Tabs.List>
        </Tabs>

        {!data && isFetching ? (
          <Center py="xl">
            <Loader />
          </Center>
        ) : data && data.rows.length === 0 ? (
          <Alert icon={<IconInfoCircle size={16} />} color="blue" variant="light">
            No {view === 'triggered' ? 'triggered' : 'near-miss'} decisions match the current
            filters in the last 30 days.
          </Alert>
        ) : (
          <Box pos="relative">
            <LoadingOverlay visible={isFetching} zIndex={5} overlayProps={{ blur: 1 }} />
            <Stack gap="sm">
              <Table striped withTableBorder highlightOnHover>
                <Table.Thead>
                  <Table.Tr>
                    <Table.Th>Label</Table.Th>
                    <Table.Th>Score</Table.Th>
                    <Table.Th>Threshold</Table.Th>
                    <Table.Th>Occurrences</Table.Th>
                    <Table.Th>Policy</Table.Th>
                    <Table.Th>Status</Table.Th>
                    <Table.Th>Last seen</Table.Th>
                  </Table.Tr>
                </Table.Thead>
                <Table.Tbody>
                  {data?.rows.map((r) => (
                    <Table.Tr key={`${r.contentHash}::${r.version}::${r.label}`}>
                      <Table.Td>
                        <Link
                          href={`/moderator/scanner-audit/${mode}/${encodeURIComponent(r.label)}`}
                          style={{ color: 'inherit', textDecoration: 'none' }}
                        >
                          <code style={{ textDecoration: 'underline', cursor: 'pointer' }}>
                            {r.label}
                          </code>
                        </Link>
                        {r.labelValue && (
                          <Text size="xs" c="dimmed" component="span" ml={4}>
                            = {r.labelValue}
                          </Text>
                        )}
                      </Table.Td>
                      <Table.Td>{r.score.toFixed(3)}</Table.Td>
                      <Table.Td>{r.threshold !== null ? r.threshold.toFixed(2) : '—'}</Table.Td>
                      <Table.Td>
                        <Text size="sm">{r.occurrences.toLocaleString()}</Text>
                      </Table.Td>
                      <Table.Td>
                        <Tooltip label={r.version || '(none)'}>
                          <Text size="xs" c="dimmed" ff="monospace">
                            {r.version ? `${r.version.slice(0, 10)}…` : '—'}
                          </Text>
                        </Tooltip>
                      </Table.Td>
                      <Table.Td>
                        <Group gap={4}>
                          {r.myVerdict && (
                            <Badge size="xs" color={verdictColor(r.myVerdict)}>
                              {verdictShort(r.myVerdict)}
                            </Badge>
                          )}
                          {!r.myVerdict && r.anyVerdict && (
                            <Tooltip label="Verdict from another moderator">
                              <Badge size="xs" color={verdictColor(r.anyVerdict)} variant="outline">
                                {verdictShort(r.anyVerdict)}
                              </Badge>
                            </Tooltip>
                          )}
                        </Group>
                      </Table.Td>
                      <Table.Td>
                        <Text size="xs" c="dimmed">
                          {new Date(r.lastSeenAt).toLocaleString()}
                        </Text>
                      </Table.Td>
                    </Table.Tr>
                  ))}
                </Table.Tbody>
              </Table>

              <Group justify="space-between">
                <Text size="xs" c="dimmed">
                  {data ? `${data.total.toLocaleString()} matching decisions` : '—'}
                </Text>
                <Pagination value={page} onChange={setPage} total={totalPages} size="sm" />
              </Group>
            </Stack>
          </Box>
        )}
      </ScannerAuditLayout>
    </>
  );
}

/**
 * Per-label moderator-review coverage for the current scanner. Shows how many
 * verdicts each label has accumulated (and the verdict split) so a mod can see
 * which labels are well-covered vs. untouched at a glance. Counts are all-time
 * and scoped to the scanner via the content snapshot's `scanner` column — a
 * shared label like `young` counts separately on the Text vs Prompt tabs.
 */
function ReviewCoveragePanel({ scanner, mode }: { scanner: Scanner; mode: ScannerAuditMode }) {
  const { data, isFetching } = trpc.scannerReview.reviewStats.useQuery({ scanner });

  const active = data?.active ?? [];
  const retired = data?.retired ?? [];
  const totalReviews = useMemo(() => active.reduce((sum, r) => sum + r.total, 0), [active]);

  return (
    <Paper withBorder p="sm" radius="md">
      <Group justify="space-between" mb="xs">
        <Title order={5}>Moderator review coverage</Title>
        {data && (
          <Text size="xs" c="dimmed">
            {totalReviews.toLocaleString()} reviews across {active.length}{' '}
            {active.length === 1 ? 'label' : 'labels'}
          </Text>
        )}
      </Group>

      {!data && isFetching ? (
        <Center py="md">
          <Loader size="sm" />
        </Center>
      ) : active.length === 0 ? (
        <Text size="sm" c="dimmed">
          No moderator reviews recorded yet for this scanner.
        </Text>
      ) : (
        <ScrollArea.Autosize mah={260}>
          <Table striped highlightOnHover>
            <Table.Thead>
              <Table.Tr>
                <Table.Th>Label</Table.Th>
                <Table.Th>Reviews</Table.Th>
                <Table.Th>Mods</Table.Th>
                <Table.Th>Verdicts</Table.Th>
                <Table.Th>Last reviewed</Table.Th>
              </Table.Tr>
            </Table.Thead>
            <Table.Tbody>
              {active.map((r) => (
                <Table.Tr key={r.label}>
                  <Table.Td>
                    <Link
                      href={`/moderator/scanner-audit/${mode}/${encodeURIComponent(r.label)}`}
                      style={{ color: 'inherit', textDecoration: 'none' }}
                    >
                      <code style={{ textDecoration: 'underline', cursor: 'pointer' }}>
                        {r.label}
                      </code>
                    </Link>
                  </Table.Td>
                  <Table.Td>
                    <Text size="sm">{r.total.toLocaleString()}</Text>
                  </Table.Td>
                  <Table.Td>
                    <Text size="sm">{r.reviewers.toLocaleString()}</Text>
                  </Table.Td>
                  <Table.Td>
                    <Group gap={4}>
                      <VerdictCount verdict={ReviewVerdict.TruePositive} count={r.truePositive} />
                      <VerdictCount verdict={ReviewVerdict.FalsePositive} count={r.falsePositive} />
                      <VerdictCount verdict={ReviewVerdict.TrueNegative} count={r.trueNegative} />
                      <VerdictCount verdict={ReviewVerdict.FalseNegative} count={r.falseNegative} />
                      <VerdictCount verdict={ReviewVerdict.Unsure} count={r.unsure} />
                    </Group>
                  </Table.Td>
                  <Table.Td>
                    <Text size="xs" c="dimmed">
                      {r.lastReviewedAt ? new Date(r.lastReviewedAt).toLocaleString() : '—'}
                    </Text>
                  </Table.Td>
                </Table.Tr>
              ))}
            </Table.Tbody>
          </Table>
        </ScrollArea.Autosize>
      )}

      {retired.length > 0 && (
        <Text size="xs" c="dimmed" mt="xs">
          Hidden — retired labels no longer produced by this scanner:{' '}
          {retired.map((r) => `${r.label} (${r.total.toLocaleString()})`).join(', ')}
        </Text>
      )}
    </Paper>
  );
}

/** A single verdict tally in the coverage table — dimmed out when zero so the
 * eye lands on the verdicts a label actually accumulated. */
function VerdictCount({ verdict, count }: { verdict: ReviewVerdict; count: number }) {
  if (count === 0)
    return (
      <Badge size="xs" variant="light" color="gray" style={{ opacity: 0.4 }}>
        {verdictShort(verdict)} 0
      </Badge>
    );
  return (
    <Badge size="xs" variant="light" color={verdictColor(verdict)}>
      {verdictShort(verdict)} {count.toLocaleString()}
    </Badge>
  );
}

function ExportButton({
  view,
  mode,
  filters,
}: {
  view: QueueView;
  mode: ScannerAuditMode;
  filters: Filters;
}) {
  const utils = trpc.useUtils();
  const [loading, setLoading] = useState(false);

  const handleExport = async () => {
    setLoading(true);
    try {
      const result = await utils.scannerReview.exportRows.fetch({
        view,
        scanner: modeToScanner(mode),
        label: filters.label || undefined,
        version: filters.version || undefined,
        limit: 50000,
        offset: 0,
      });
      const csv = toCsv(result.rows);
      const blob = new Blob([csv], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `scanner-audit-${mode}-${view}-${Date.now()}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      showErrorNotification({ title: 'Export failed', error: err as Error });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button
      variant="default"
      leftSection={<IconDownload size={14} />}
      loading={loading}
      onClick={handleExport}
      size="xs"
    >
      Export CSV
    </Button>
  );
}

function verdictColor(v: ReviewVerdict): string {
  switch (v) {
    case ReviewVerdict.TruePositive:
    case ReviewVerdict.TrueNegative:
      return 'green';
    case ReviewVerdict.FalsePositive:
    case ReviewVerdict.FalseNegative:
      return 'red';
    case ReviewVerdict.Unsure:
    default:
      return 'gray';
  }
}

function verdictShort(v: ReviewVerdict): string {
  switch (v) {
    case ReviewVerdict.TruePositive:
      return 'TP';
    case ReviewVerdict.FalsePositive:
      return 'FP';
    case ReviewVerdict.TrueNegative:
      return 'TN';
    case ReviewVerdict.FalseNegative:
      return 'FN';
    case ReviewVerdict.Unsure:
      return '?';
  }
}

function toCsv(rows: QueueRow[]): string {
  if (rows.length === 0) return '';
  const headers = [
    'contentHash',
    'version',
    'label',
    'scanner',
    'entityType',
    'labelValue',
    'modelVersion',
    'score',
    'threshold',
    'triggered',
    'occurrences',
    'firstSeenAt',
    'lastSeenAt',
    'durationMs',
    'workflowIds',
    'entityIds',
    'matchedText',
    'matchedPositivePrompt',
    'matchedNegativePrompt',
    'myVerdict',
    'anyVerdict',
  ] as const;
  const lines = [headers.join(',')];
  for (const r of rows) {
    const cells: (string | number | null)[] = [
      r.contentHash,
      r.version,
      r.label,
      r.scanner,
      r.entityType,
      r.labelValue,
      r.modelVersion,
      r.score,
      r.threshold,
      r.triggered,
      r.occurrences,
      r.firstSeenAt,
      r.lastSeenAt,
      r.durationMs,
      r.workflowIds.join('|'),
      r.entityIds.join('|'),
      r.matchedText.join('|'),
      r.matchedPositivePrompt.join('|'),
      r.matchedNegativePrompt.join('|'),
      r.myVerdict ?? '',
      r.anyVerdict ?? '',
    ];
    lines.push(cells.map(csvCell).join(','));
  }
  return lines.join('\n');
}

function csvCell(v: string | number | null): string {
  if (v === null || v === undefined) return '';
  const s = String(v);
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export default Page(ScannerAuditTablePage);
