// src/components/Buzz/PricingSlotHistory.tsx
import { Anchor, Divider, Loader, Popover, Stack, Table, Text } from '@mantine/core';
import { useState } from 'react';
import { PRICING_SLOT_EXPLAINER, formatFeeRatio } from '@civitai/buzz';
import type { RouterOutput } from '~/types/router';
import { formatDate } from '~/utils/date-helpers';
import { trpc } from '~/utils/trpc';

// What each price charges now — the ledger stores no amount, so this is the version's current price
// rather than the one it was priced at.
function priceLabel({
  licensingFee,
  accessPrice,
  generationPrice,
}: {
  licensingFee: number | null;
  accessPrice: number | null;
  generationPrice: number | null;
}) {
  const parts: string[] = [];
  // formatFeeRatio, not the raw per-image number: the default fee is 0.1/image, which every other
  // surface shows as "1 ⚡ / 10 images".
  if (licensingFee) parts.push(`${formatFeeRatio(licensingFee)} license fee`);
  if (accessPrice) parts.push(`${accessPrice.toLocaleString()} ⚡ access`);
  if (generationPrice) parts.push(`${generationPrice.toLocaleString()} ⚡ generation`);
  // Not 'it will be released on your next save': the row is still here, and a release can refuse for
  // reasons we can't distinguish — releasePricingSlot fails closed when it can't tell.
  return parts.length ? parts.join(' · ') : 'No current price — this slot has not been returned';
}

// A deleted model keeps its slot but has no page, and a name we no longer hold means the row outlived
// its entity — say which without claiming a cause we cannot check.
function slotLabel({
  modelName,
  versionName,
  entityId,
}: {
  modelName: string | null;
  versionName: string | null;
  entityId: number;
}) {
  if (!modelName) return `#${entityId} — no longer available`;
  return versionName ? `${modelName} · ${versionName}` : modelName;
}

/** The slots the creator has spent, newest first. Opened from the monthly counter. */
export function PricingSlotHistory() {
  const [opened, setOpened] = useState(false);
  const { data, isLoading } = trpc.modelVersion.getPricingSlots.useQuery(undefined, {
    enabled: opened,
  });

  const thisMonth = data?.filter((slot) => slot.countsThisMonth) ?? [];
  const earlier = data?.filter((slot) => !slot.countsThisMonth) ?? [];

  return (
    <Popover
      width={420}
      withArrow
      withinPortal
      shadow="md"
      position="bottom-start"
      opened={opened}
      onChange={setOpened}
    >
      <Popover.Target>
        <Anchor component="button" type="button" size="xs" onClick={() => setOpened((o) => !o)}>
          What used my slots?
        </Anchor>
      </Popover.Target>
      <Popover.Dropdown mah={420} style={{ overflowY: 'auto' }}>
        <Stack gap="xs">
          <Text size="xs" c="dimmed">
            {PRICING_SLOT_EXPLAINER}
          </Text>
          {isLoading && <Loader size="xs" />}
          {!isLoading && data?.length === 0 && (
            <Text size="xs">You haven&apos;t priced any model versions yet.</Text>
          )}
          {!!data?.length && (
            <>
              <SlotTable
                title={`This month · ${thisMonth.length} ${
                  thisMonth.length === 1 ? 'slot' : 'slots'
                }`}
                slots={thisMonth}
              />
              {earlier.length > 0 && (
                <>
                  <Divider />
                  <SlotTable title="Priced earlier — not counted this month" slots={earlier} />
                </>
              )}
              <Text size="xs" c="dimmed">
                Amounts are what each version charges now. A price changed after it was set shows
                its current value.
              </Text>
            </>
          )}
        </Stack>
      </Popover.Dropdown>
    </Popover>
  );
}

type Slot = RouterOutput['modelVersion']['getPricingSlots'][number];

function SlotTable({ title, slots }: { title: string; slots: Slot[] }) {
  return (
    <Stack gap={4}>
      <Text size="xs" fw={600}>
        {title}
      </Text>
      {slots.length === 0 ? (
        <Text size="xs" c="dimmed">
          Nothing yet.
        </Text>
      ) : (
        <Table fz="xs" verticalSpacing={4} horizontalSpacing="xs">
          <Table.Tbody>
            {slots.map((slot) => (
              <Table.Tr key={`${slot.entityType}-${slot.entityId}`}>
                <Table.Td c="dimmed" style={{ whiteSpace: 'nowrap' }}>
                  {formatDate(slot.createdAt)}
                </Table.Td>
                <Table.Td>
                  {slot.modelId ? (
                    <Anchor
                      href={`/models/${slot.modelId}?modelVersionId=${slot.entityId}`}
                      target="_blank"
                    >
                      {slotLabel(slot)}
                    </Anchor>
                  ) : (
                    <Text size="xs" c="dimmed">
                      {slotLabel(slot)}
                    </Text>
                  )}
                  <Text size="xs" c="dimmed">
                    {priceLabel(slot)}
                  </Text>
                </Table.Td>
              </Table.Tr>
            ))}
          </Table.Tbody>
        </Table>
      )}
    </Stack>
  );
}

// apps/creator-studio/src/lib/components/PricingSlotHistory.svelte
<script lang="ts">
  import { PRICING_SLOT_EXPLAINER } from '@civitai/buzz';
  import { formatFeeRatio } from '$lib/monetization/fee';
  import { modelUrl } from '$lib/model-url';
  import type { PricingSlotEntry } from '$lib/server/monetization/pricing-slot';

  let { slots }: { slots: PricingSlotEntry[] } = $props();

  const thisMonth = $derived(slots.filter((s) => s.countsThisMonth));
  const earlier = $derived(slots.filter((s) => !s.countsThisMonth));

  // Pinned locale, like date-range.ts and impressions.ts: this renders on the server too, and a
  // locale-dependent string is a hydration mismatch.
  const dateFormat = new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });

  // A deleted model keeps its slot but has no page, and a name we no longer hold means the row outlived
  // its entity — say which without claiming a cause we cannot check.
  function slotLabel(slot: PricingSlotEntry): string {
    if (!slot.modelName) return `#${slot.entityId} — no longer available`;
    return slot.versionName ? `${slot.modelName} · ${slot.versionName}` : slot.modelName;
  }

  // The ledger stores no amount, so these are the version's CURRENT prices, not the ones it was
  // priced at.
  function priceLabel(slot: PricingSlotEntry): string {
    const parts: string[] = [];
    // formatFeeRatio, not the raw per-image number: the default fee is 0.1/image, which every other
    // surface shows as "1 ⚡ / 10 images".
    if (slot.licensingFee) parts.push(`${formatFeeRatio(slot.licensingFee)} license fee`);
    if (slot.accessPrice) parts.push(`${slot.accessPrice.toLocaleString()} ⚡ access`);
    if (slot.generationPrice) parts.push(`${slot.generationPrice.toLocaleString()} ⚡ generation`);
    // Not 'released on your next save': the row is still here, and a release can refuse for reasons we
    // can't distinguish — releasePricingSlot fails closed when it can't tell.
    return parts.length ? parts.join(' · ') : 'No current price — this slot has not been returned';
  }
</script>

{#snippet rows(entries: PricingSlotEntry[])}
  <ul class="flex flex-col gap-1.5">
    {#each entries as slot (slot.entityId)}
      <li class="flex flex-wrap items-baseline gap-x-2">
        <span class="w-24 shrink-0 text-dark-2">{dateFormat.format(slot.createdAt)}</span>
        {#if slot.modelId}
          <a
            class="text-blue-3 hover:underline"
            href={modelUrl(slot.modelId, { nsfw: slot.modelNsfw, nsfwLevel: slot.modelNsfwLevel })}
            target="_blank"
            rel="noreferrer"
          >
            {slotLabel(slot)}
          </a>
        {:else}
          <span class="text-dark-2">{slotLabel(slot)}</span>
        {/if}
        <span class="text-dark-2">{priceLabel(slot)}</span>
      </li>
    {/each}
  </ul>
{/snippet}

<div class="flex flex-col gap-3 text-xs">
  <p class="text-dark-2">{PRICING_SLOT_EXPLAINER}</p>
  {#if slots.length === 0}
    <p class="text-dark-2">You haven't priced any model versions yet.</p>
  {:else}
    <div class="flex flex-col gap-1.5">
      <span class="font-semibold text-white">
        This month · {thisMonth.length}
        {thisMonth.length === 1 ? 'slot' : 'slots'}
      </span>
      {#if thisMonth.length === 0}
        <span class="text-dark-2">Nothing yet.</span>
      {:else}
        {@render rows(thisMonth)}
      {/if}
    </div>
    {#if earlier.length > 0}
      <div class="flex flex-col gap-1.5">
        <span class="font-semibold text-white">Priced earlier — not counted this month</span>
        {@render rows(earlier)}
      </div>
    {/if}
    <p class="text-dark-2">
      Amounts are what each version charges now. A price changed after it was set shows its current
      value.
    </p>
  {/if}
</div>
