// src/components/Subscriptions/TierCapsTable.tsx
import { Stack, Table, Text } from '@mantine/core';
import { MAX_LICENSING_FEE, VIDEO_CAP_MULTIPLIER, tierAllowanceRows } from '@civitai/buzz';

// Rendered from `tierAllowanceRows()` rather than transcribed, so these numbers cannot drift from what
// the server enforces. Creator Studio shows the same table (TierCapsTable.svelte) off the same helper.
const fmt = (n: number | null) => (n === null ? 'Unlimited' : n.toLocaleString());

export const TierCapsTable = () => {
  const rows = tierAllowanceRows();

  return (
    <Stack gap="lg">
      <Stack gap={4}>
        <Text size="sm" fw={600}>
          Model versions you can monetize each month{' '}
          <Text component="span" size="sm" c="dimmed" fw={400}>
            — a licensing fee or paid access
          </Text>
        </Text>
        <Table.ScrollContainer minWidth={320}>
          <Table striped withTableBorder verticalSpacing="xs" fz="sm">
            <Table.Thead>
              <Table.Tr>
                <Table.Th>Tier</Table.Th>
                <Table.Th ta="right">Monetized / month</Table.Th>
              </Table.Tr>
            </Table.Thead>
            <Table.Tbody>
              {rows.map((row) => (
                <Table.Tr key={row.tier}>
                  <Table.Td fw={600}>{row.label}</Table.Td>
                  <Table.Td ta="right">{fmt(row.monthlyPrices)}</Table.Td>
                </Table.Tr>
              ))}
            </Table.Tbody>
          </Table>
        </Table.ScrollContainer>
      </Stack>

      <Stack gap={4}>
        <Text size="xs" c="dimmed">
          A licensing fee or a permanent paid-access price each count once, per version, the first
          time you set one. Changing or removing a price you have already set costs nothing, and a
          timed early-access window never counts.
        </Text>
        <Text size="xs" c="dimmed">
          How much you charge is the same at every tier: up to {MAX_LICENSING_FEE.toLocaleString()}{' '}
          ⚡ per generation as a licensing fee (
          {(MAX_LICENSING_FEE * VIDEO_CAP_MULTIPLIER).toLocaleString()} ⚡ for video models), and
          any price you like for paid access.
        </Text>
      </Stack>
    </Stack>
  );
};

// apps/creator-studio/src/lib/components/TierCapsTable.svelte
<script lang="ts">
  import { tierAllowanceRows } from '$lib/monetization/paid-access';
  import { MAX_LICENSING_FEE, maxLicensingFeeCeiling } from '$lib/monetization/fee';

  // `capTier` is what the allowance resolves to, not the display tier — a lapsed membership keeps its
  // label but is allowed what free is allowed, and the highlighted row has to match what the write path
  // will actually permit.
  let { capTier = 'free', class: className = '' }: { capTier?: string; class?: string } = $props();

  const rows = tierAllowanceRows();
  const fmt = (n: number | null) => (n === null ? '∞' : n.toLocaleString());

  const rowCls = (tier: string) => (tier === capTier ? 'bg-dark-5/60 text-white' : 'text-dark-1');
  const cellCls = 'whitespace-nowrap py-1.5 pr-3 text-right tabular-nums';
</script>

<div class={className}>
  <div class="mb-3 overflow-x-auto">
    <p class="mb-1 text-xs font-medium text-white">
      Model versions you can monetize each month
      <span class="font-normal text-dark-2">— a licensing fee or paid access</span>
    </p>
    <table class="w-full min-w-72 border-collapse text-left text-xs">
      <thead>
        <tr class="text-dark-2">
          <th class="py-1.5 pr-3 font-medium">Tier</th>
          <th class="py-1.5 pr-2 text-right font-medium">Monetized / month</th>
        </tr>
      </thead>
      <tbody>
        {#each rows as row (row.tier)}
          <tr class={rowCls(row.tier)}>
            <td class="whitespace-nowrap rounded-l py-1.5 pl-2 pr-3 font-medium">
              {row.label}
              {#if row.tier === capTier}<span class="ml-1 text-blue-4">· you</span>{/if}
            </td>
            <td class="{cellCls} rounded-r pr-2">{fmt(row.monthlyPrices)}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>

  <p class="text-xs text-dark-2">
    A licensing fee or a permanent paid-access price each count once, per version, the first time
    you set one. Changing or removing a price you have already set costs nothing, and a timed
    early-access window never counts.
  </p>
  <p class="mt-1 text-xs text-dark-2">
    How much you charge is the same at every tier: up to {MAX_LICENSING_FEE.toLocaleString()} ⚡ per generation
    as a licensing fee ({maxLicensingFeeCeiling('video').toLocaleString()} ⚡ for video models), and any
    price you like for paid access.
  </p>
</div>
