// src/pages/moderator/minor-hash-matches.tsx
import {
  Alert,
  Anchor,
  Badge,
  Button,
  Code,
  Container,
  Group,
  Loader,
  Stack,
  Tabs,
  Text,
  Title,
} from '@mantine/core';
import { openConfirmModal } from '@mantine/modals';
import { IconExternalLink } from '@tabler/icons-react';
import type { MRT_ColumnDef } from 'mantine-react-table';
import { MantineReactTable } from 'mantine-react-table';
import { useMemo, useState } from 'react';
import { EdgeMedia } from '~/components/EdgeMedia/EdgeMedia';
import { NextLink } from '~/components/NextLink/NextLink';
import type {
  MinorHashMatchDetail,
  MinorHashReviewRow,
} from '~/server/services/minor-hash.service';
import { createServerSideProps } from '~/server/utils/server-side-helpers';
import type { MediaType } from '~/shared/utils/prisma/enums';
import { formatDate } from '~/utils/date-helpers';
import { showErrorNotification } from '~/utils/notifications';
import { trpc } from '~/utils/trpc';

export const getServerSideProps = createServerSideProps({ requireModerator: true });

// The full queue is fetched in one request; this is a safety cap, not a page size.
const limit = 1000;

// Deep-links to the version whose file actually carries the matching hash — a
// model's default version is often not the one that matched.
const modelHref = (modelId: number, versionId?: number | null) =>
  `/models/${modelId}?view=basic${versionId ? `&modelVersionId=${versionId}` : ''}`;

// Published is the one that still needs a decision — the copy is live and
// downloadable right now — so it reads as active rather than resolved.
const statusColors: Record<string, string> = {
  Published: 'blue',
  Scheduled: 'cyan',
  Draft: 'gray',
  Unpublished: 'gray',
  UnpublishedViolation: 'yellow',
  Deleted: 'red',
};

type PanelModel = {
  id: number;
  name: string;
  versionId?: number | null;
  status: string;
  username: string | null;
  userId: number;
};

type PanelMatch = {
  id: number;
  name: string | null;
  versionId?: number | null;
  userId?: number | null;
  hash: string;
};

function MatchDetail({
  detail,
  model,
  match,
  isLoading,
}: {
  detail: MinorHashMatchDetail | null;
  model: PanelModel;
  match: PanelMatch | null;
  isLoading: boolean;
}) {
  if (isLoading) return <Loader size="sm" />;

  return (
    <div className="flex flex-wrap gap-6 p-2">
      <div className="flex gap-3">
        {detail?.modelCoverUrl && (
          <EdgeMedia
            src={detail.modelCoverUrl}
            type={(detail.modelCoverType ?? 'image') as MediaType}
            width={140}
          />
        )}
        <Stack gap={2}>
          <Text fw={600}>{model.name}</Text>
          <Text size="xs" c="dimmed">
            Uploaded {detail?.modelCreatedAt ? formatDate(detail.modelCreatedAt) : 'unknown'} ·{' '}
            {model.status}
          </Text>
          <Text size="xs" c="dimmed">
            {model.username ?? model.userId} · {detail?.uploaderModelCount ?? 0} models · joined{' '}
            {detail?.uploaderJoinedAt ? formatDate(detail.uploaderJoinedAt) : 'unknown'}
          </Text>
          <Anchor
            component={NextLink}
            href={modelHref(model.id, model.versionId)}
            target="_blank"
            size="xs"
          >
            <Group gap={4}>
              Open model <IconExternalLink size={12} />
            </Group>
          </Anchor>
        </Stack>
      </div>

      {match ? (
        <>
          <div className="flex gap-3">
            {detail?.minorModelCoverUrl && (
              <EdgeMedia
                src={detail.minorModelCoverUrl}
                type={(detail.minorModelCoverType ?? 'image') as MediaType}
                width={140}
              />
            )}
            <Stack gap={2}>
              <Text fw={600}>Matches: {match.name ?? `#${match.id}`}</Text>
              <Text size="xs" c="dimmed">
                {detail?.minorUsername ?? match.userId ?? 'unknown'} ·{' '}
                {detail?.minorModelStatus ?? 'unknown'}
              </Text>
              {/* The gap between this and the copy's upload date is the evidence; a
                  "Deleted" badge alone doesn't show they happened minutes apart. */}
              {detail?.minorModelDeletedAt && (
                <Text size="xs" c="dimmed">
                  Deleted {formatDate(detail.minorModelDeletedAt)}
                </Text>
              )}
              {/* Only 2 of ~13.5k minor-locked models have a setMinor ModActivity row, so
                  rendering a placeholder here would read as missing data on every row. */}
              {detail?.minorFlaggedAt && (
                <Text size="xs" c="dimmed">
                  Set minor {formatDate(detail.minorFlaggedAt)}
                  {detail.minorFlaggedByUsername ? ` by ${detail.minorFlaggedByUsername}` : ''}
                </Text>
              )}
              <Anchor
                component={NextLink}
                href={modelHref(match.id, match.versionId)}
                target="_blank"
                size="xs"
              >
                <Group gap={4}>
                  Open flagged model <IconExternalLink size={12} />
                </Group>
              </Anchor>
            </Stack>
          </div>

          <Stack gap={2}>
            <Text size="xs" fw={600}>
              Shared SHA256
            </Text>
            <Code>{match.hash}</Code>
          </Stack>
        </>
      ) : (
        <Alert color="yellow" title="No matching flagged model">
          <Text size="sm">
            Nothing a moderator has flagged minor still shares a file with this model. The match is
            resolved live, so this means the model it matched has since been unflagged or its hashes
            were permanently deleted — worth checking before you keep the flag.
          </Text>
        </Alert>
      )}
    </div>
  );
}

function ReviewDetailPanel({ row }: { row: MinorHashReviewRow }) {
  const { data, isLoading } = trpc.moderator.models.queryMinorHashMatchDetail.useQuery({
    modelId: row.modelId,
    minorModelId: row.minorModelId,
  });

  return (
    <MatchDetail
      isLoading={isLoading}
      detail={data ?? null}
      model={{
        id: row.modelId,
        name: row.modelName,
        versionId: row.modelVersionId,
        status: row.status,
        username: row.username,
        userId: row.userId,
      }}
      match={{
        id: row.minorModelId,
        name: row.minorModelName,
        versionId: row.minorModelVersionId,
        userId: row.minorUserId,
        hash: row.hash,
      }}
    />
  );
}

type AutoFlaggedRow = {
  modelId: number;
  modelName: string;
  userId: number;
  username: string | null;
  status: string;
  flaggedAt: Date;
  prevNsfw: boolean | null;
  prevGalleryLevel: number | null;
};

// The flag is already in force on these rows, so the evidence matters more here
// than on the review queue, where nothing has happened to the model yet.
function AutoFlaggedDetailPanel({ row }: { row: AutoFlaggedRow }) {
  const { data, isLoading } = trpc.moderator.models.queryAutoFlaggedMinorDetail.useQuery({
    modelId: row.modelId,
  });
  const match = data?.match;

  return (
    <MatchDetail
      isLoading={isLoading}
      detail={data?.detail ?? null}
      model={{
        id: row.modelId,
        name: row.modelName,
        versionId: match?.modelVersionId,
        status: row.status,
        username: row.username,
        userId: row.userId,
      }}
      match={
        match
          ? {
              id: match.minorModelId,
              name: match.minorModelName,
              versionId: match.minorModelVersionId,
              hash: match.hash,
            }
          : null
      }
    />
  );
}

// Models the scan hook flagged with no human in the loop. Confirming records the
// moderator's own setMinor, which both clears the row from here and stops a bulk
// rollback from undoing it.
function AutoFlaggedTable() {
  const queryUtils = trpc.useUtils();
  const { data, isLoading, isFetching } =
    trpc.moderator.models.queryAutoFlaggedMinorModels.useQuery({ limit });
  const items = useMemo(() => data?.items ?? [], [data]);

  const onSettled = async () => {
    await queryUtils.moderator.models.queryAutoFlaggedMinorModels.invalidate();
    await queryUtils.moderator.models.queryMinorHashMatches.invalidate();
  };
  const onError = (error: { message: string }) =>
    showErrorNotification({ title: 'Action failed', error });

  const confirmMutation = trpc.moderator.models.confirmMinorHashAutoFlag.useMutation({
    onSuccess: onSettled,
    onError,
  });
  const revertMutation = trpc.moderator.models.revertMinorHashAutoFlag.useMutation({
    onSuccess: onSettled,
    onError,
  });

  const columns = useMemo<MRT_ColumnDef<AutoFlaggedRow>[]>(
    () => [
      {
        id: 'modelName',
        header: 'Model',
        accessorKey: 'modelName',
        size: 300,
        Cell: ({ row: { original } }) => (
          <Anchor
            component={NextLink}
            href={modelHref(original.modelId)}
            target="_blank"
            lineClamp={2}
          >
            {original.modelName}
          </Anchor>
        ),
      },
      {
        id: 'username',
        header: 'Uploader',
        accessorKey: 'username',
        size: 150,
        Cell: ({ row: { original } }) =>
          original.username ? (
            <Anchor
              component={NextLink}
              href={`/user/${original.username}`}
              target="_blank"
              lineClamp={1}
            >
              {original.username}
            </Anchor>
          ) : (
            <Text>{original.userId}</Text>
          ),
      },
      {
        id: 'status',
        header: 'Status',
        accessorKey: 'status',
        size: 170,
        filterVariant: 'multi-select',
        Cell: ({ row: { original } }) => (
          <Badge
            size="sm"
            tt="none"
            color={statusColors[original.status] ?? 'gray'}
            variant="light"
          >
            {original.status}
          </Badge>
        ),
      },
      {
        id: 'flaggedAt',
        header: 'Auto-flagged',
        accessorFn: (row) => new Date(row.flaggedAt),
        sortingFn: 'datetime',
        size: 140,
        enableColumnFilter: false,
        Cell: ({ row: { original } }) => (
          <Text size="xs">{original.flaggedAt ? formatDate(original.flaggedAt) : '—'}</Text>
        ),
      },
      {
        id: 'actions',
        header: '',
        size: 200,
        enableSorting: false,
        enableColumnFilter: false,
        enableColumnActions: false,
        Cell: ({ row: { original } }) => (
          <Group gap="xs" justify="flex-end" wrap="nowrap">
            <Button
              size="compact-sm"
              loading={
                confirmMutation.isPending && confirmMutation.variables?.id === original.modelId
              }
              onClick={() => confirmMutation.mutate({ id: original.modelId })}
            >
              Keep flagged
            </Button>
            <Button
              size="compact-sm"
              variant="light"
              color="red"
              loading={
                revertMutation.isPending && revertMutation.variables?.id === original.modelId
              }
              onClick={() =>
                openConfirmModal({
                  title: 'Revert automatic minor flag',
                  centered: true,
                  labels: { confirm: 'Revert', cancel: 'Cancel' },
                  confirmProps: { color: 'red' },
                  children: (
                    <Text size="sm">
                      Unflag <strong>{original.modelName}</strong> and restore the settings it had
                      before the scan flagged it
                      {original.prevNsfw ? ', including its NSFW flag' : ''}
                      {original.prevGalleryLevel != null
                        ? ` and gallery level ${original.prevGalleryLevel}`
                        : ''}
                      .
                    </Text>
                  ),
                  onConfirm: () => revertMutation.mutate({ id: original.modelId }),
                })
              }
            >
              Revert
            </Button>
          </Group>
        ),
      },
    ],
    [confirmMutation, revertMutation]
  );

  return (
    <>
      {data?.truncated && (
        <Alert color="yellow" title="List truncated">
          Showing the first {limit} auto-flagged models.
        </Alert>
      )}
      <MantineReactTable
        columns={columns}
        data={items}
        enableStickyHeader
        enableColumnPinning
        enableSorting
        enableColumnFilters
        enableGlobalFilter
        enableFacetedValues
        layoutMode="grid"
        renderDetailPanel={({ row }) => <AutoFlaggedDetailPanel row={row.original} />}
        renderEmptyRowsFallback={() => (
          <Text p="xl" ta="center" c="dimmed">
            Nothing auto-flagged awaiting review.
          </Text>
        )}
        mantineTableContainerProps={{ style: { maxHeight: 600 } }}
        initialState={{
          density: 'xs',
          columnPinning: { right: ['actions'] },
          pagination: { pageIndex: 0, pageSize: 25 },
          showGlobalFilter: true,
          showColumnFilters: true,
        }}
        state={{ isLoading, showProgressBars: isFetching }}
      />
    </>
  );
}

export default function MinorHashMatches() {
  const queryUtils = trpc.useUtils();
  const [tab, setTab] = useState<string>('pending');
  const { data: autoData } = trpc.moderator.models.queryAutoFlaggedMinorModels.useQuery({ limit });
  const autoCount = autoData?.items.length ?? 0;

  const { data, isFetching, isLoading } = trpc.moderator.models.queryMinorHashMatches.useQuery({
    limit,
  });

  const items = useMemo(() => data?.items ?? [], [data]);

  const onSettled = async () => {
    await queryUtils.moderator.models.queryMinorHashMatches.invalidate();
  };
  const onError = (error: { message: string }) =>
    showErrorNotification({ title: 'Action failed', error });

  const setMinorMutation = trpc.model.setMinor.useMutation({ onSuccess: onSettled, onError });
  const dismissMutation = trpc.moderator.models.dismissMinorHashMatch.useMutation({
    onSuccess: onSettled,
    onError,
  });

  const columns = useMemo<MRT_ColumnDef<MinorHashReviewRow>[]>(
    () => [
      {
        id: 'modelName',
        header: 'Model',
        accessorKey: 'modelName',
        size: 235,
        Cell: ({ row: { original } }) => (
          <Anchor
            component={NextLink}
            href={modelHref(original.modelId, original.modelVersionId)}
            target="_blank"
            lineClamp={2}
          >
            {original.modelName}
          </Anchor>
        ),
      },
      {
        id: 'username',
        header: 'Uploader',
        accessorKey: 'username',
        size: 130,
        Cell: ({ row: { original } }) =>
          original.username ? (
            <Anchor
              component={NextLink}
              href={`/user/${original.username}`}
              target="_blank"
              lineClamp={1}
            >
              {original.username}
            </Anchor>
          ) : (
            <Text>{original.userId}</Text>
          ),
      },
      {
        id: 'status',
        header: 'Status',
        accessorKey: 'status',
        // Wide enough for "UnpublishedViolation" — truncating it loses the
        // distinction from a plain "Unpublished", which changes the mod's call.
        size: 170,
        filterVariant: 'multi-select',
        Cell: ({ row: { original } }) => (
          <Badge
            size="sm"
            tt="none"
            color={statusColors[original.status] ?? 'gray'}
            variant="light"
          >
            {original.status}
          </Badge>
        ),
      },
      {
        id: 'createdAt',
        header: 'Uploaded',
        accessorFn: (row) => new Date(row.createdAt),
        sortingFn: 'datetime',
        size: 125,
        enableColumnFilter: false,
        Cell: ({ row: { original } }) => (
          <Text size="xs">{original.createdAt ? formatDate(original.createdAt) : '—'}</Text>
        ),
      },
      {
        id: 'minorModelName',
        header: 'Matches flagged model',
        accessorKey: 'minorModelName',
        size: 215,
        Cell: ({ row: { original } }) => (
          <Anchor
            component={NextLink}
            href={modelHref(original.minorModelId, original.minorModelVersionId)}
            target="_blank"
            lineClamp={2}
          >
            {original.minorModelName ?? `#${original.minorModelId}`}
          </Anchor>
        ),
      },
      {
        // Actions stay pinned right so they're reachable without horizontal scroll.
        id: 'actions',
        header: '',
        size: 195,
        enableSorting: false,
        enableColumnFilter: false,
        enableColumnActions: false,
        Cell: ({ row: { original } }) => (
          <Group gap="xs" justify="flex-end" wrap="nowrap">
            <Button
              size="compact-sm"
              color="red"
              loading={
                setMinorMutation.isPending && setMinorMutation.variables?.id === original.modelId
              }
              onClick={() =>
                openConfirmModal({
                  title: 'Set model as minor',
                  centered: true,
                  labels: { confirm: 'Set as Minor', cancel: 'Cancel' },
                  confirmProps: { color: 'red' },
                  children: (
                    <Stack gap="xs">
                      <Text size="sm">
                        Flag <strong>{original.modelName}</strong> as minor? This forces the model
                        SFW-only, resets its gallery browsing level, and locks those properties.
                      </Text>
                      <Text size="sm" c="dimmed">
                        The current settings are saved first, so this can be undone — but only by a
                        rollback naming this model specifically. A blanket rollback deliberately
                        skips manual flags so it can&apos;t revert a moderator&apos;s decision.
                      </Text>
                    </Stack>
                  ),
                  onConfirm: () => setMinorMutation.mutate({ id: original.modelId, minor: true }),
                })
              }
            >
              Set as Minor
            </Button>
            <Button
              size="compact-sm"
              variant="light"
              loading={
                dismissMutation.isPending && dismissMutation.variables?.id === original.modelId
              }
              onClick={() => dismissMutation.mutate({ id: original.modelId })}
            >
              Dismiss
            </Button>
          </Group>
        ),
      },
    ],
    [setMinorMutation, dismissMutation]
  );

  return (
    <Container size="xl">
      <Stack gap="md">
        <div>
          <Title order={1}>Minor hash matches</Title>
          <Text c="dimmed" size="sm">
            Models sharing a byte-identical weight file with a model a moderator already flagged
            minor. Different-uploader matches wait for review here; same-uploader matches are
            flagged automatically at scan time and are listed under Auto-flagged.
          </Text>
        </div>

        <Tabs value={tab} onChange={(value) => setTab(value ?? 'pending')}>
          <Tabs.List>
            <Tabs.Tab value="pending">Pending review</Tabs.Tab>
            <Tabs.Tab value="auto">Auto-flagged{autoCount ? ` (${autoCount})` : ''}</Tabs.Tab>
          </Tabs.List>
        </Tabs>

        {tab === 'auto' && <AutoFlaggedTable />}

        {tab === 'pending' && (
          <>
            {data?.truncated && (
              <Alert color="yellow" title="Queue truncated">
                Showing the first {limit} matches. Work the queue down to see the rest.
              </Alert>
            )}

            <MantineReactTable
              columns={columns}
              data={items}
              enableStickyHeader
              enableColumnPinning
              // The whole queue is loaded, so client-side sorting, filtering and paging
              // act on every row rather than on a partial window.
              enableSorting
              enableColumnFilters
              enableGlobalFilter
              enableFacetedValues
              layoutMode="grid"
              renderDetailPanel={({ row }) => <ReviewDetailPanel row={row.original} />}
              renderEmptyRowsFallback={() => (
                <Text p="xl" ta="center" c="dimmed">
                  No matches pending review.
                </Text>
              )}
              mantineTableContainerProps={{ style: { maxHeight: 600 } }}
              initialState={{
                density: 'xs',
                columnPinning: { right: ['actions'] },
                pagination: { pageIndex: 0, pageSize: 25 },
                showGlobalFilter: true,
                showColumnFilters: true,
              }}
              state={{ isLoading, showProgressBars: isFetching }}
            />
          </>
        )}
      </Stack>
    </Container>
  );
}

// apps/moderator/src/routes/models/minor-hash-matches/+page.svelte
<script lang="ts">
  import { applyAction, enhance } from '$app/forms';
  import { page } from '$app/state';
  import type { SubmitFunction } from '@sveltejs/kit';
  import { SvelteMap, SvelteSet } from 'svelte/reactivity';
  import { Badge } from '@civitai/ui/components/ui/badge/index.js';
  import { Button } from '@civitai/ui/components/ui/button/index.js';
  import { cn } from '@civitai/ui/utils.js';
  import EdgeMedia from '$lib/components/EdgeMedia.svelte';
  import { LINK_CLASS, dateTime, num } from '$lib/format';
  import { userLookupUrl } from '$lib/entity-url';
  import type { ActionData, PageData } from './$types';

  let { data, form }: { data: PageData; form: ActionData } = $props();

  // Rows are shaped per tab; the fields read below exist only on the tab that supplies them.
  type Row = PageData['items'][number] & Record<string, unknown>;
  const rows = $derived(data.items as Row[]);
  const n = (v: unknown) => (typeof v === 'number' ? v : null);
  const s = (v: unknown) => (typeof v === 'string' ? v : null);

  const tabHref = (tab: string) => {
    const url = new URL(page.url);
    url.searchParams.set('tab', tab);
    // Expanded rows and the limit both describe the tab you are leaving.
    url.searchParams.delete('limit');
    return url.pathname + url.search;
  };

  // modelId → verdict. Optimistic: the row dims and states the outcome. Cleared whenever the queue
  // itself changes, so a stale mark can never describe a different row.
  const acted = new SvelteMap<number, string>();
  const expanded = new SvelteSet<number>();
  $effect(() => {
    data.items;
    acted.clear();
    expanded.clear();
  });

  // A failed action must UNDO its optimistic mark. Leaving it makes the moderator's own record wrong,
  // and the row they then skip is the one that failed.
  const submit =
    (modelId: number, verdict: string): SubmitFunction =>
    () => {
      acted.set(modelId, verdict);
      return async ({ result, update }) => {
        // applyAction is what puts a `fail()` payload into `form`. Without it the error banner never
        // renders and a REFUSED verdict looks exactly like an applied one — which on this page means a
        // moderator believing they signed off on a minor flag that never happened.
        if (result.type !== 'success') {
          acted.delete(modelId);
          await applyAction(result);
          return;
        }
        await update({ invalidateAll: true });
      };
    };

  type Detail = {
    match: {
      minorModelId: number;
      minorModelName: string | null;
      minorModelVersionId: number | null;
      hash: string;
      /** The version of THIS model that carried the matched hash. Only the auto/appeals tabs get it
       *  from here — the Pending row already knows its own. */
      modelVersionId: number | null;
    } | null;
    detail: {
      modelCoverUrl: string | null;
      modelCoverType: string | null;
      modelCreatedAt: string | null;
      uploaderModelCount: number;
      uploaderJoinedAt: string | null;
      minorModelCoverUrl: string | null;
      minorModelCoverType: string | null;
      minorModelStatus: string | null;
      minorModelDeletedAt: string | null;
      minorUsername: string | null;
      minorFlaggedAt: string | null;
      minorFlaggedByUsername: string | null;
    } | null;
  };

  // Fetched on expand and cached per row. The promise is stored, not the resolved value, so the
  // template can await it — and a second expand of the same row does not refetch.
  // Aliased so the generic does not end in `>>`, which the script parser reads as a shift operator
  // and rejects — svelte-check accepts it, so the only symptom is a 500 from the dev server.
  type DetailRequest = Promise<Detail>;
  const details = new SvelteMap<number, DetailRequest>();
  function toggle(row: Row) {
    const id = Number(row.modelId);
    if (expanded.has(id)) return expanded.delete(id);
    expanded.add(id);
    if (details.has(id)) return;
    const seed = n(row.minorModelId);
    const q = seed ? `?minorModelId=${seed}` : '';
    details.set(
      id,
      fetch(`/api/minor-hash-detail/${id}${q}`).then((r) => {
        if (!r.ok) throw new Error(String(r.status));
        return r.json() as Promise<Detail>;
      })
    );
  }

  // Version-specific, and `view=basic`, matching the href the main app builds. Landing on the model
  // with no version leaves a moderator guessing which of several files carried the matched hash.
  //
  // `versionId: number | null` rather than an OPTIONAL parameter: `versionId?:` in an arrow function
  // makes the Svelte script parser read the `?` as a ternary and fail the whole route with
  // "Parse failure: Expression expected" at a column that does not exist in the file. svelte-check
  // and esbuild both accept it, so nothing catches this except loading the page.
  const modelHref = (modelId: number, versionId: number | null) => {
    const base = `${data.civitaiUrl}/models/${modelId}?view=basic`;
    return versionId ? `${base}&modelVersionId=${versionId}` : base;
  };

  // Cached server-side and fetched here: the Pending count alone is ~10s, which is not a price to pay
  // on every page render to label three tabs.
  let counts = $state<{ pending: number; auto: number; appeals: number } | null>(null);
  $effect(() => {
    fetch('/api/minor-queue-counts')
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => (counts = d))
      .catch(() => (counts = null));
  });

  const pageHref = (n: number) => {
    const url = new URL(page.url);
    url.searchParams.set('page', String(n));
    return url.pathname + url.search;
  };
  const firstShown = $derived(data.offset + 1);
  const lastShown = $derived(data.offset + rows.length);
</script>

<header class="page-header">
  <h1>Minor Hash Matches</h1>
  <p>
    Models sharing a file hash with something a moderator flagged as depicting a minor, what the
    scanner flagged on its own, and the owners contesting it.
  </p>
</header>

<nav class="mb-4 flex gap-1 border-b border-dark-4">
  {#each data.tabs as t (t.value)}
    <a
      href={tabHref(t.value)}
      class={cn(
        'flex items-center gap-2 rounded-t-md px-4 py-2 text-sm',
        data.tab === t.value
          ? 'border-b-2 border-blue-500 text-white'
          : 'text-dark-2 hover:text-dark-0'
      )}
    >
      {t.label}
      <!-- Absent until loaded rather than a placeholder zero: "Appeals 0" is a claim, and on these
           queues it is the one a moderator would act on by not looking. -->
      {#if counts}
        <Badge variant="secondary">{num(counts[t.value])}</Badge>
      {/if}
    </a>
  {/each}
</nav>

{#if form && 'error' in form && form.error}
  <div class="mb-4 rounded-md border border-red-500/30 bg-red-500/10 p-2 text-sm text-red-300" role="alert">
    {form.error}
  </div>
{/if}

{#if rows.length === 0}
  <p class="text-sm text-dark-2">
    {data.tab === 'pending'
      ? 'No unreviewed hash matches.'
      : data.tab === 'auto'
        ? 'Nothing flagged automatically inside the review window.'
        : 'No open appeals against a minor flag.'}
  </p>
{:else}
  <ul class="space-y-2">
    {#each rows as row (row.modelId)}
      {@const modelId = Number(row.modelId)}
      {@const verdict = acted.get(modelId)}
      <li
        class={cn(
          'rounded-lg border border-dark-4 bg-dark-6 p-4 transition-opacity',
          verdict && 'opacity-50'
        )}
      >
        <div class="flex flex-wrap items-baseline gap-x-2">
          <a
            href={modelHref(modelId, n(row.modelVersionId))}
            target="_blank"
            rel="noreferrer"
            class="font-medium {LINK_CLASS}"
          >
            {s(row.modelName) ?? `#${modelId}`}
          </a>
          <code class="text-xs text-dark-2">#{modelId}</code>
          <Badge variant="secondary">{s(row.status) ?? 'unknown'}</Badge>
          {#if row.minor === false}
            <!-- Reverting from the Auto-flagged tab leaves the appeal open; the row has to say the
                 flag is already gone or a moderator upholds against nothing. -->
            <Badge variant="outline">no longer flagged</Badge>
          {/if}
          {#if s(row.flagSource)}
            <Badge variant="outline">
              {s(row.flagSource)}{s(row.flagConfirmedFrom) ? ` (was ${s(row.flagConfirmedFrom)})` : ''}
            </Badge>
          {/if}
          {#if row.username}
            <a href={userLookupUrl(Number(row.userId))} class="text-xs {LINK_CLASS}">
              {s(row.username)}
            </a>
          {/if}
          {#if s(row.flaggedAt)}
            <span class="text-xs text-dark-2">flagged {dateTime(s(row.flaggedAt))}</span>
          {/if}
          {#if s(row.createdAt)}
            <span class="text-xs text-dark-2">uploaded {dateTime(s(row.createdAt))}</span>
          {/if}
        </div>

        {#if s(row.appealMessage)}
          <p class="mt-2 rounded-md bg-dark-7 p-2 text-sm text-dark-0">{s(row.appealMessage)}</p>
          <p class="mt-1 text-xs text-dark-2">appealed {dateTime(s(row.appealCreatedAt))}</p>
        {/if}

        {#if s(row.hash)}
          <p class="mt-2 text-xs break-all text-dark-2">
            Matches
            {#if n(row.minorModelId)}
              <a
                href={modelHref(Number(row.minorModelId), n(row.minorModelVersionId))}
                target="_blank"
                rel="noreferrer"
                class={LINK_CLASS}
              >
                {s(row.minorModelName) ?? `#${n(row.minorModelId)}`}
              </a>
            {/if}
            on <code>{s(row.hash)}</code>
          </p>
        {/if}

        {#if row.prevNsfw != null || n(row.prevGalleryLevel) != null}
          <p class="mt-1 text-xs text-dark-2">
            Before the flag: NSFW {row.prevNsfw ? 'on' : 'off'}{n(row.prevGalleryLevel) != null
              ? `, gallery level ${n(row.prevGalleryLevel)}`
              : ''}
          </p>
        {/if}

        <div class="mt-3 flex flex-wrap items-center gap-2">
          <Button size="xs" variant="outline" onclick={() => toggle(row)}>
            {expanded.has(modelId) ? 'Hide detail' : 'Detail'}
          </Button>

          {#if verdict}
            <span class="text-sm text-dark-2">{verdict}</span>
          {:else if data.tab === 'pending'}
            <form method="POST" action="?/setMinor" use:enhance={submit(modelId, 'Flagged as minor')}>
              <input type="hidden" name="modelId" value={modelId} />
              <Button type="submit" size="xs" variant="destructive">Set as minor</Button>
            </form>
            <form method="POST" action="?/dismiss" use:enhance={submit(modelId, 'Dismissed')}>
              <input type="hidden" name="modelId" value={modelId} />
              <Button type="submit" size="xs" variant="outline">Dismiss match</Button>
            </form>
          {:else if data.tab === 'auto'}
            <form method="POST" action="?/confirm" use:enhance={submit(modelId, 'Kept flagged')}>
              <input type="hidden" name="modelId" value={modelId} />
              <Button type="submit" size="xs">Keep flagged</Button>
            </form>
            <form method="POST" action="?/revert" use:enhance={submit(modelId, 'Reverted')}>
              <input type="hidden" name="modelId" value={modelId} />
              <Button type="submit" size="xs" variant="destructive">Revert</Button>
            </form>
          {:else}
            <form method="POST" action="?/upholdAppeal" use:enhance={submit(modelId, 'Appeal rejected')}>
              <input type="hidden" name="modelId" value={modelId} />
              <Button type="submit" size="xs">Uphold flag</Button>
            </form>
            <form method="POST" action="?/overturnAppeal" use:enhance={submit(modelId, 'Appeal approved')}>
              <input type="hidden" name="modelId" value={modelId} />
              <Button type="submit" size="xs" variant="destructive">Overturn</Button>
            </form>
          {/if}
        </div>

        {#if expanded.has(modelId)}
          {#await details.get(modelId)}
            <p class="mt-3 text-sm text-dark-2">Loading detail…</p>
          {:then payload}
            {#if payload?.detail}
              {@const d = payload.detail}
              {@const m = payload.match}
              {@const ownVersion = n(row.modelVersionId) ?? m?.modelVersionId ?? null}
              {@const seedId = n(row.minorModelId) ?? m?.minorModelId ?? null}
              {@const seedVersion = n(row.minorModelVersionId) ?? m?.minorModelVersionId ?? null}
              {@const hash = s(row.hash) ?? m?.hash ?? null}
              <div class="mt-3 grid gap-4 border-t border-dark-4 pt-3 sm:grid-cols-2">
                <div>
                  <h4 class="mb-1 text-xs tracking-wide text-dark-2 uppercase">This model</h4>
                  {#if d.modelCoverUrl}
                    <EdgeMedia
                      src={d.modelCoverUrl}
                      type={(d.modelCoverType ?? 'image') as 'image' | 'video'}
                      width={300}
                      class="mb-2 max-h-48 rounded-md"
                    />
                  {/if}
                  <p class="text-xs text-dark-2">
                    Uploaded {dateTime(d.modelCreatedAt)} · {s(row.status) ?? 'unknown'}
                  </p>
                  <p class="text-xs text-dark-2">
                    {s(row.username) ?? row.userId} · {num(d.uploaderModelCount)} model{d.uploaderModelCount ===
                    1
                      ? ''
                      : 's'} · joined {dateTime(d.uploaderJoinedAt)}
                  </p>
                  <a
                    href={modelHref(modelId, ownVersion ?? null)}
                    target="_blank"
                    rel="noreferrer"
                    class="mt-1 inline-block text-xs {LINK_CLASS}"
                  >
                    Open model ↗
                  </a>
                </div>

                {#if seedId}
                  <div>
                    <h4 class="mb-1 text-xs tracking-wide text-dark-2 uppercase">The flagged source</h4>
                    {#if d.minorModelCoverUrl}
                      <EdgeMedia
                        src={d.minorModelCoverUrl}
                        type={(d.minorModelCoverType ?? 'image') as 'image' | 'video'}
                        width={300}
                        class="mb-2 max-h-48 rounded-md"
                      />
                    {/if}
                    <p class="text-xs text-dark-2">
                      {d.minorUsername ?? 'unknown'} · {d.minorModelStatus ?? 'unknown'}
                    </p>
                    <!-- The GAP between this and the copy's upload date is the evidence; a "deleted"
                         badge alone does not show they happened minutes apart. -->
                    {#if d.minorModelDeletedAt}
                      <p class="text-xs text-dark-2">Deleted {dateTime(d.minorModelDeletedAt)}</p>
                    {/if}
                    <!-- Only 2 of ~13.5k minor-locked models carry a setMinor ModActivity row, so a
                         placeholder here would read as missing data on nearly every row. -->
                    {#if d.minorFlaggedAt}
                      <p class="text-xs text-dark-2">
                        Set minor {dateTime(d.minorFlaggedAt)}{d.minorFlaggedByUsername
                          ? ` by ${d.minorFlaggedByUsername}`
                          : ''}
                      </p>
                    {/if}
                    <a
                      href={modelHref(seedId, seedVersion ?? null)}
                      target="_blank"
                      rel="noreferrer"
                      class="mt-1 inline-block text-xs {LINK_CLASS}"
                    >
                      Open flagged model ↗
                    </a>
                  </div>
                {:else if (s(row.flagConfirmedFrom) ?? s(row.flagSource) ?? 'auto') === 'manual'}
                  <div class="rounded-md border border-blue-500/30 bg-blue-500/10 p-3 text-sm text-blue-200">
                    <strong class="block">No hash match</strong>
                    A moderator flagged this model directly rather than the automation matching it
                    against a known minor model, so there is no match to show — nothing is missing here.
                  </div>
                {:else}
                  <div class="rounded-md border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-200">
                    <strong class="block">No matching flagged model</strong>
                    Nothing a moderator has flagged minor still shares a file with this model. The match
                    is resolved live, so the model it matched has since been unflagged or its hashes were
                    deleted — worth checking before you keep the flag.
                  </div>
                {/if}
              </div>

              {#if hash}
                <div class="mt-3">
                  <h4 class="text-xs font-semibold text-dark-2">Shared SHA256</h4>
                  <code class="text-xs break-all text-dark-0">{hash}</code>
                </div>
              {/if}
            {:else}
              <p class="mt-3 text-sm text-dark-2">No detail for this model.</p>
            {/if}
          {:catch}
            <p class="mt-3 text-sm text-red-300">Could not load the detail for this model.</p>
          {/await}
        {/if}
      </li>
    {/each}
  </ul>

  <div class="mt-4 flex flex-wrap items-center gap-3 text-sm">
    {#if data.page > 1}
      <a href={pageHref(data.page - 1)} class={LINK_CLASS}>← Previous</a>
    {/if}
    <span class="text-dark-2">
      {num(firstShown)}–{num(lastShown)}{counts ? ` of ${num(counts[data.tab])}` : ''}
    </span>
    {#if data.hasMore}
      <a href={pageHref(data.page + 1)} class={LINK_CLASS}>Next →</a>
    {/if}
  </div>

  {#if data.hasMore || data.page > 1}
    <!-- Offset paging over a queue being drained skips rows: acting on page 1 shifts everything up,
         so page 2 then starts past something never seen. -->
    <p class="mt-1 text-xs text-dark-3">
      After actioning rows, reload this page rather than paging forward — the queue shifts underneath
      the page boundary.
    </p>
  {/if}
{/if}
