// apps/moderator/src/routes/blocklists/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { goto } from '$app/navigation';
  import type { SubmitFunction } from '@sveltejs/kit';
  import { Tabs, TabsList, TabsTrigger } from '@civitai/ui/components/ui/tabs/index.js';
  import { Textarea } from '@civitai/ui/components/ui/textarea/index.js';
  import { Button } from '@civitai/ui/components/ui/button/index.js';
  import { BLOCKLIST_TYPES, BLOCKLIST_DESCRIPTIONS, humanizeBlocklistType } from '$lib/blocklist';
  import type { ActionData, PageData } from './$types';

  let { data, form }: { data: PageData; form: ActionData } = $props();

  let mode = $state<'add' | 'remove'>('add');
  let text = $state('');

  // Reset the input + mode whenever a different type tab loads.
  $effect(() => {
    data.type;
    text = '';
    mode = 'add';
  });

  const sortedItems = $derived([...data.blocklist.data].sort());

  function setMode(next: 'add' | 'remove') {
    mode = next;
    text = '';
  }

  function stageForRemoval(item: string) {
    if (mode !== 'remove') return;
    const current = text
      .split(',')
      .map((s) => s.trim())
      .filter((s) => s.length > 0);
    if (!current.includes(item)) text = [...current, item].join(', ');
  }

  const submit: SubmitFunction = () => async ({ result, update }) => {
    if (result.type === 'success') text = '';
    await update(); // re-runs load → fresh blocklist (and the shared Redis cache is already updated)
  };
</script>

<header class="page-header">
  <h1>Blocklists</h1>
</header>

<Tabs value={data.type} onValueChange={(v) => v && goto(`?type=${v}`)} class="mb-4">
  <TabsList>
    {#each BLOCKLIST_TYPES as t (t)}
      <TabsTrigger value={t}>{humanizeBlocklistType(t)}</TabsTrigger>
    {/each}
  </TabsList>
</Tabs>

{#if BLOCKLIST_DESCRIPTIONS[data.type]}
  <p class="mb-4 max-w-xl text-sm text-muted-foreground">{BLOCKLIST_DESCRIPTIONS[data.type]}</p>
{/if}

{#if form?.error}
  <div class="mb-4 max-w-xl rounded-md border border-red-500/30 bg-red-500/10 p-2 text-sm text-red-300">
    {form.error}
  </div>
{:else if form?.success}
  <div class="mb-4 max-w-xl rounded-md border border-teal-500/30 bg-teal-500/10 p-2 text-sm text-teal-300">
    {form.action === 'add' ? 'Added' : 'Removed'} {form.count} item{form.count === 1 ? '' : 's'}.
  </div>
{/if}

<div class="flex max-w-xl flex-col gap-4">
  <div class="flex flex-col gap-2 rounded-xl border p-3">
    {#if data.blocklist.id}
      <div class="flex gap-1">
        <Button size="sm" variant={mode === 'add' ? 'default' : 'outline'} onclick={() => setMode('add')}>
          Add
        </Button>
        <Button
          size="sm"
          variant={mode === 'remove' ? 'default' : 'outline'}
          onclick={() => setMode('remove')}
        >
          Remove
        </Button>
      </div>
    {/if}

    <form
      method="POST"
      action={mode === 'add' ? '?/add' : '?/remove'}
      use:enhance={submit}
      class="flex flex-col gap-2"
    >
      <input type="hidden" name="type" value={data.type} />
      {#if data.blocklist.id}<input type="hidden" name="id" value={data.blocklist.id} />{/if}
      <Textarea
        name="blocklist"
        bind:value={text}
        placeholder={mode === 'add'
          ? 'Add comma-delimited items to blocklist'
          : 'Remove comma-delimited items from blocklist'}
      />
      <div class="flex justify-end">
        <Button type="submit" disabled={text.trim().length === 0}>Submit</Button>
      </div>
    </form>
  </div>

  {#if sortedItems.length === 0}
    <p class="text-sm text-muted-foreground">No items in this blocklist.</p>
  {:else}
    <div class="flex flex-col gap-2">
      <span class="text-sm font-medium">{humanizeBlocklistType(data.type)} ({sortedItems.length})</span>
      <div class="flex flex-wrap gap-2">
        {#each sortedItems as item (item)}
          <button
            type="button"
            disabled={mode !== 'remove'}
            onclick={() => stageForRemoval(item)}
            class="rounded-md bg-muted px-3 py-1 text-xs font-medium text-muted-foreground ring-1 ring-inset ring-border {mode ===
            'remove'
              ? 'cursor-pointer hover:bg-red-500/15 hover:text-red-300'
              : 'cursor-default'}"
          >
            {item}
          </button>
        {/each}
      </div>
    </div>
  {/if}
</div>

// src/pages/moderator/blocklists.tsx
import { Button, SegmentedControl, Tabs, Text, Title } from '@mantine/core';
import { forwardRef, useRef, useState } from 'react';
import * as z from 'zod';
import { TwCard } from '~/components/TwCard/TwCard';
import { TwLoader } from '~/components/TwLoader/TwLoader';
import { Form, InputTextArea, useForm } from '~/libs/form';
import { BlocklistType } from '~/server/common/enums';
import type { BlocklistDTO } from '~/server/services/blocklist.service';
import { splitUppercase } from '~/utils/string-helpers';
import { trpc } from '~/utils/trpc';
import clsx from 'clsx';
import { Page } from '~/components/AppLayout/Page';

const schema = z.object({
  blocklist: z.string(),
});

function BlocklistsPage() {
  const tabs = Object.values(BlocklistType).sort();
  const [tab, setTab] = useState(tabs[0]);
  const [state, setState] = useState<string>('add');
  const stateRef = useRef<string>(state);

  const { data, isLoading } = trpc.blocklist.getBlocklist.useQuery({ type: tab });

  const form = useForm({ schema });

  function handleStateChange(value: string) {
    setState(value);
    stateRef.current = value;
    form.reset();
  }

  function addItemToRemove(value: string) {
    if (stateRef.current === 'add') return;
    const currentValue =
      form
        .getValues()
        .blocklist?.split(',')
        .filter((x) => x.length > 0) ?? [];
    form.setValue('blocklist', [...currentValue, value].join(','));
  }

  return (
    <div className="container flex max-w-sm flex-col gap-3">
      <Title>Blocklists</Title>
      <Tabs
        variant="pills"
        value={tab}
        onChange={(value) => setTab((value as BlocklistType) ?? tabs[0])}
      >
        <Tabs.List>
          {tabs.map((tab) => (
            <Tabs.Tab key={tab} value={tab}>
              {splitUppercase(tab)}
            </Tabs.Tab>
          ))}
        </Tabs.List>
      </Tabs>

      {isLoading ? (
        <div className="flex items-center justify-center p-5">
          <TwLoader />
        </div>
      ) : (
        <>
          <TwCard className="gap-2 border p-3">
            {!!data?.id && (
              <SegmentedControl
                value={state}
                onChange={handleStateChange}
                data={[
                  { label: 'Add', value: 'add' },
                  { label: 'Remove', value: 'remove' },
                ]}
              />
            )}

            <AddOrRemoveItems tab={tab} data={data} state={state} form={form} />
          </TwCard>
          {!data?.data.length ? (
            <Text>No items found for this blocklist</Text>
          ) : (
            <div className="flex flex-col gap-2">
              <Text>{splitUppercase(tab)}</Text>
              <div className="flex flex-wrap gap-2">
                {data.data.sort().map((item) => {
                  return (
                    <span
                      key={item}
                      className={clsx(
                        'inline-flex  items-center rounded-md bg-gray-1 px-3 py-1 text-xs font-medium text-gray-6 ring-1 ring-inset ring-gray-5/10 dark:bg-dark-6 dark:text-dark-1 dark:ring-dark-3/10',
                        { ['cursor-pointer']: state === 'remove' }
                      )}
                      onClick={() => addItemToRemove(item)}
                    >
                      {item}
                    </span>
                  );
                })}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}

const AddOrRemoveItems = forwardRef<
  HTMLTextAreaElement,
  { tab: BlocklistType; data?: BlocklistDTO; state: string; form: any }
>(({ tab, data, state, form }, ref) => {
  const queryUtils = trpc.useUtils();

  const upsert = trpc.blocklist.upsertBlocklist.useMutation({
    onSuccess: () => {
      queryUtils.blocklist.getBlocklist.invalidate({ type: tab });
      form.reset();
    },
  });
  const remove = trpc.blocklist.removeItems.useMutation({
    onSuccess: () => {
      queryUtils.blocklist.getBlocklist.invalidate({ type: tab });
      form.reset();
    },
  });

  function handleSubmit({ blocklist }: z.infer<typeof schema>) {
    const items = blocklist
      .split(',')
      .map((item) => item.trim())
      .filter((x) => x.length > 0);
    if (state === 'add') upsert.mutate({ id: data?.id, type: tab, blocklist: items });
    else if (state === 'remove' && !!data?.id) remove.mutate({ id: data.id, items: items });
  }

  return (
    <Form form={form} onSubmit={handleSubmit} className="flex flex-col gap-2">
      <InputTextArea
        ref={ref}
        name="blocklist"
        placeholder={`${
          state === 'add' ? 'Add comma delimited items to' : 'Remove comma delimited items from'
        } blocklist`}
      />
      <div className="flex justify-end">
        <Button type="submit" loading={upsert.isLoading || remove.isLoading}>
          Submit
        </Button>
      </div>
    </Form>
  );
});

AddOrRemoveItems.displayName = 'AddOrRemoveItems';

export default Page(BlocklistsPage, { features: (features) => features.blocklists });
